/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const ConversationStatus: core.serialization.Schema<
    serializers.tts.ConversationStatus.Raw,
    Speechify.tts.ConversationStatus
> = core.serialization.enum_(["pending", "active", "completed", "failed"]);

export declare namespace ConversationStatus {
    export type Raw = "pending" | "active" | "completed" | "failed";
}
