/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { ConversationStatus } from "./ConversationStatus";
import { ConversationTransport } from "./ConversationTransport";

export const Conversation: core.serialization.ObjectSchema<
    serializers.tts.Conversation.Raw,
    Speechify.tts.Conversation
> = core.serialization.object({
    id: core.serialization.string(),
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    roomName: core.serialization.property("room_name", core.serialization.string()),
    roomSid: core.serialization.property("room_sid", core.serialization.string().optional()),
    status: ConversationStatus,
    transport: ConversationTransport,
    startedAt: core.serialization.property("started_at", core.serialization.date().optionalNullable()),
    endedAt: core.serialization.property("ended_at", core.serialization.date().optionalNullable()),
    durationMs: core.serialization.property("duration_ms", core.serialization.number().optionalNullable()),
    costCents: core.serialization.property("cost_cents", core.serialization.number().optionalNullable()),
    recordingUrl: core.serialization.property("recording_url", core.serialization.string().optionalNullable()),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace Conversation {
    export interface Raw {
        id: string;
        agent_id: string;
        room_name: string;
        room_sid?: string | null;
        status: ConversationStatus.Raw;
        transport: ConversationTransport.Raw;
        started_at?: (string | null) | null;
        ended_at?: (string | null) | null;
        duration_ms?: (number | null) | null;
        cost_cents?: (number | null) | null;
        recording_url?: (string | null) | null;
        metadata?: Record<string, unknown> | null;
    }
}
