/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const ConversationTransport: core.serialization.Schema<
    serializers.tts.ConversationTransport.Raw,
    Speechify.tts.ConversationTransport
> = core.serialization.enum_(["web", "sip"]);

export declare namespace ConversationTransport {
    export type Raw = "web" | "sip";
}
