/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { CreatedVoiceGender } from "./CreatedVoiceGender";
import { CreateVoiceModel } from "./CreateVoiceModel";
import { CreatedVoiceType } from "./CreatedVoiceType";

export const CreatedVoice: core.serialization.ObjectSchema<
    serializers.tts.CreatedVoice.Raw,
    Speechify.tts.CreatedVoice
> = core.serialization.object({
    avatarImage: core.serialization.property("avatar_image", core.serialization.string().optional()),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    gender: CreatedVoiceGender.optional(),
    locale: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    models: core.serialization.list(CreateVoiceModel).optional(),
    type: CreatedVoiceType.optional(),
});

export declare namespace CreatedVoice {
    export interface Raw {
        avatar_image?: string | null;
        display_name?: string | null;
        gender?: CreatedVoiceGender.Raw | null;
        locale?: string | null;
        id?: string | null;
        models?: CreateVoiceModel.Raw[] | null;
        type?: CreatedVoiceType.Raw | null;
    }
}
