/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const DynamicVariableType: core.serialization.Schema<
    serializers.tts.DynamicVariableType.Raw,
    Speechify.tts.DynamicVariableType
> = core.serialization.enum_(["string", "number", "boolean", "json"]);

export declare namespace DynamicVariableType {
    export type Raw = "string" | "number" | "boolean" | "json";
}
