/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const EvaluationCriterion: core.serialization.ObjectSchema<
    serializers.tts.EvaluationCriterion.Raw,
    Speechify.tts.EvaluationCriterion
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace EvaluationCriterion {
    export interface Raw {
        id: string;
        name: string;
        description: string;
    }
}
