/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const GetSpeechResponseAudioFormat: core.serialization.Schema<
    serializers.tts.GetSpeechResponseAudioFormat.Raw,
    Speechify.tts.GetSpeechResponseAudioFormat
> = core.serialization.enum_(["wav", "mp3", "ogg", "aac", "pcm"]);

export declare namespace GetSpeechResponseAudioFormat {
    export type Raw = "wav" | "mp3" | "ogg" | "aac" | "pcm";
}
