/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const GetVoiceType: core.serialization.Schema<serializers.tts.GetVoiceType.Raw, Speechify.tts.GetVoiceType> =
    core.serialization.enum_(["shared", "personal"]);

export declare namespace GetVoiceType {
    export type Raw = "shared" | "personal";
}
