/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const GetVoiceLanguage: core.serialization.ObjectSchema<
    serializers.tts.GetVoiceLanguage.Raw,
    Speechify.tts.GetVoiceLanguage
> = core.serialization.object({
    locale: core.serialization.string().optional(),
    previewAudio: core.serialization.property("preview_audio", core.serialization.string().optional()),
});

export declare namespace GetVoiceLanguage {
    export interface Raw {
        locale?: string | null;
        preview_audio?: string | null;
    }
}
