/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const Invite: core.serialization.ObjectSchema<serializers.tts.Invite.Raw, Speechify.tts.Invite> =
    core.serialization.object({
        id: core.serialization.string(),
        email: core.serialization.string(),
        invitedBy: core.serialization.property("invited_by", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        expiresAt: core.serialization.property("expires_at", core.serialization.date()),
        acceptedAt: core.serialization.property("accepted_at", core.serialization.date().optional()),
        revokedAt: core.serialization.property("revoked_at", core.serialization.date().optional()),
        token: core.serialization.string().optional(),
    });

export declare namespace Invite {
    export interface Raw {
        id: string;
        email: string;
        invited_by: string;
        created_at: string;
        expires_at: string;
        accepted_at?: string | null;
        revoked_at?: string | null;
        token?: string | null;
    }
}
