/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { Conversation } from "./Conversation";

export const ListConversationsResponse: core.serialization.ObjectSchema<
    serializers.tts.ListConversationsResponse.Raw,
    Speechify.tts.ListConversationsResponse
> = core.serialization.object({
    conversations: core.serialization.list(Conversation),
});

export declare namespace ListConversationsResponse {
    export interface Raw {
        conversations: Conversation.Raw[];
    }
}
