/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { AgentTestRun } from "./AgentTestRun";

export const ListAgentTestRunsResponse: core.serialization.ObjectSchema<
    serializers.tts.ListAgentTestRunsResponse.Raw,
    Speechify.tts.ListAgentTestRunsResponse
> = core.serialization.object({
    runs: core.serialization.list(AgentTestRun),
});

export declare namespace ListAgentTestRunsResponse {
    export interface Raw {
        runs: AgentTestRun.Raw[];
    }
}
