/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { KnowledgeBaseDocument } from "./KnowledgeBaseDocument";

export const ListKnowledgeBaseDocumentsResponse: core.serialization.ObjectSchema<
    serializers.tts.ListKnowledgeBaseDocumentsResponse.Raw,
    Speechify.tts.ListKnowledgeBaseDocumentsResponse
> = core.serialization.object({
    documents: core.serialization.list(KnowledgeBaseDocument),
});

export declare namespace ListKnowledgeBaseDocumentsResponse {
    export interface Raw {
        documents: KnowledgeBaseDocument.Raw[];
    }
}
