/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { Agent } from "./Agent";

export const ListAgentsResponse: core.serialization.ObjectSchema<
    serializers.tts.ListAgentsResponse.Raw,
    Speechify.tts.ListAgentsResponse
> = core.serialization.object({
    agents: core.serialization.list(Agent),
});

export declare namespace ListAgentsResponse {
    export interface Raw {
        agents: Agent.Raw[];
    }
}
