/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { Tool } from "./Tool";

export const ListToolsResponse: core.serialization.ObjectSchema<
    serializers.tts.ListToolsResponse.Raw,
    Speechify.tts.ListToolsResponse
> = core.serialization.object({
    tools: core.serialization.list(Tool),
});

export declare namespace ListToolsResponse {
    export interface Raw {
        tools: Tool.Raw[];
    }
}
