/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const MemberRole: core.serialization.Schema<serializers.tts.MemberRole.Raw, Speechify.tts.MemberRole> =
    core.serialization.enum_(["owner", "admin", "member"]);

export declare namespace MemberRole {
    export type Raw = "owner" | "admin" | "member";
}
