/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { MessageRole } from "./MessageRole";

export const Message: core.serialization.ObjectSchema<serializers.tts.Message.Raw, Speechify.tts.Message> =
    core.serialization.object({
        id: core.serialization.string(),
        conversationId: core.serialization.property("conversation_id", core.serialization.string()),
        role: MessageRole,
        content: core.serialization.string(),
        toolName: core.serialization.property("tool_name", core.serialization.string().optionalNullable()),
        toolArgs: core.serialization.property(
            "tool_args",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
        ),
        toolResult: core.serialization.property("tool_result", core.serialization.unknown().optionalNullable()),
        startedAt: core.serialization.property("started_at", core.serialization.date()),
        endedAt: core.serialization.property("ended_at", core.serialization.date().optionalNullable()),
    });

export declare namespace Message {
    export interface Raw {
        id: string;
        conversation_id: string;
        role: MessageRole.Raw;
        content: string;
        tool_name?: (string | null) | null;
        tool_args?: (Record<string, unknown> | null) | null;
        tool_result?: (unknown | null) | null;
        started_at: string;
        ended_at?: (string | null) | null;
    }
}
