/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { SystemToolConfigBuiltin } from "./SystemToolConfigBuiltin";
import { ToolParam } from "./ToolParam";

export const SystemToolConfig: core.serialization.ObjectSchema<
    serializers.tts.SystemToolConfig.Raw,
    Speechify.tts.SystemToolConfig
> = core.serialization.object({
    builtin: SystemToolConfigBuiltin,
    params: core.serialization.list(ToolParam).optional(),
    builtinConfig: core.serialization.property(
        "builtin_config",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
});

export declare namespace SystemToolConfig {
    export interface Raw {
        builtin: SystemToolConfigBuiltin.Raw;
        params?: ToolParam.Raw[] | null;
        builtin_config?: Record<string, unknown> | null;
    }
}
