/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { Tenant } from "./Tenant";

export const TenantsListResponse: core.serialization.ObjectSchema<
    serializers.tts.TenantsListResponse.Raw,
    Speechify.tts.TenantsListResponse
> = core.serialization.object({
    tenants: core.serialization.list(Tenant),
});

export declare namespace TenantsListResponse {
    export interface Raw {
        tenants: Tenant.Raw[];
    }
}
