/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";
import { TenantPlan } from "./TenantPlan";
import { TenantDataRegion } from "./TenantDataRegion";

export const Tenant: core.serialization.ObjectSchema<serializers.tts.Tenant.Raw, Speechify.tts.Tenant> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        plan: TenantPlan,
        dataRegion: core.serialization.property("data_region", TenantDataRegion),
        hipaaMode: core.serialization.property("hipaa_mode", core.serialization.boolean()),
        zeroRetention: core.serialization.property("zero_retention", core.serialization.boolean()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace Tenant {
    export interface Raw {
        id: string;
        name: string;
        plan: TenantPlan.Raw;
        data_region: TenantDataRegion.Raw;
        hipaa_mode: boolean;
        zero_retention: boolean;
        created_at: string;
        updated_at: string;
    }
}
