/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const TenantDataRegion: core.serialization.Schema<
    serializers.tts.TenantDataRegion.Raw,
    Speechify.tts.TenantDataRegion
> = core.serialization.enum_(["us", "eu", "in"]);

export declare namespace TenantDataRegion {
    export type Raw = "us" | "eu" | "in";
}
