/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const TestType: core.serialization.Schema<serializers.tts.TestType.Raw, Speechify.tts.TestType> =
    core.serialization.enum_(["scenario", "tool", "simulation"]);

export declare namespace TestType {
    export type Raw = "scenario" | "tool" | "simulation";
}
