/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const ToolMock: core.serialization.ObjectSchema<serializers.tts.ToolMock.Raw, Speechify.tts.ToolMock> =
    core.serialization.object({
        toolName: core.serialization.property("tool_name", core.serialization.string()),
        argsMatch: core.serialization.property("args_match", core.serialization.string().optional()),
        response: core.serialization.unknown(),
    });

export declare namespace ToolMock {
    export interface Raw {
        tool_name: string;
        args_match?: string | null;
        response?: unknown;
    }
}
