/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Speechify from "../../../../api/index";
import * as core from "../../../../core";

export const ToolParamType: core.serialization.Schema<serializers.tts.ToolParamType.Raw, Speechify.tts.ToolParamType> =
    core.serialization.enum_(["string", "number", "integer", "boolean"]);

export declare namespace ToolParamType {
    export type Raw = "string" | "number" | "integer" | "boolean";
}
