// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Speechify from "../../../index.js";

export declare namespace ModelsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * The catalog of selectable text-to-speech models and their metadata.
 * Static platform reference data consumed when choosing a `model` for
 * synthesis.
 */
export class ModelsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ModelsClient.Options>;

    constructor(options: ModelsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List the text-to-speech models available for synthesis. Drive a model
     * picker from this response, then pass a model `id` as the `model`
     * parameter to POST /v1/audio/speech or /v1/audio/stream. The response
     * marks the default model (used when a request omits `model`), the
     * routes each model may be passed to, and which voices it accepts.
     * Multi-speaker models arrive in a separate `dialogue_models` array
     * because they are valid only on POST /v1/audio/dialogue. Returns
     * the full set in a single response: the model catalog is static
     * platform reference data, so it is intentionally not paginated.
     *
     * @param {ModelsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.ForbiddenError}
     * @throws {@link Speechify.TooManyRequestsError}
     * @throws {@link Speechify.InternalServerError}
     *
     * @example
     *     await client.models.list()
     */
    public list(requestOptions?: ModelsClient.RequestOptions): core.HttpResponsePromise<Speechify.ModelsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: ModelsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Speechify.ModelsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Speechify-Version": requestOptions?.version ?? this._options?.version ?? "2026-09-29",
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/audio/models",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Speechify.ModelsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Speechify.ForbiddenError(_response.error.body as Speechify.Error_, _response.rawResponse);
                case 429:
                    throw new Speechify.TooManyRequestsError(
                        _response.error.body as Speechify.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Speechify.InternalServerError(
                        _response.error.body as Speechify.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/audio/models");
    }
}
