/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "email"
 *     }
 */
export interface CreateInviteRequest {
    /** Email of the person to invite. Validated as an RFC 5322 address. */
    email: string;
}
