/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         role: "owner"
 *     }
 */
export interface UpdateMemberRoleRequest {
    role: Speechify.tts.MemberRole;
}
