/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateAgentTestFolderRequest: core.serialization.Schema<
    serializers.tts.CreateAgentTestFolderRequest.Raw,
    Speechify.tts.CreateAgentTestFolderRequest
> = core.serialization.object({
    name: core.serialization.string(),
    parentFolderId: core.serialization.property("parent_folder_id", core.serialization.string().optionalNullable()),
});

export declare namespace CreateAgentTestFolderRequest {
    export interface Raw {
        name: string;
        parent_folder_id?: (string | null) | null;
    }
}
