/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateAgentRequest: core.serialization.Schema<
    serializers.tts.CreateAgentRequest.Raw,
    Speechify.tts.CreateAgentRequest
> = core.serialization.object({
    name: core.serialization.string(),
    slug: core.serialization.string().optional(),
    prompt: core.serialization.string().optional(),
    firstMessage: core.serialization.property("first_message", core.serialization.string().optional()),
    language: core.serialization.string().optional(),
    llmModel: core.serialization.property("llm_model", core.serialization.string().optional()),
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    temperature: core.serialization.number().optional(),
    config: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    isPublic: core.serialization.property("is_public", core.serialization.boolean().optional()),
    allowedOrigins: core.serialization.property(
        "allowed_origins",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    hostnameAllowlist: core.serialization.property(
        "hostname_allowlist",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    memoryEnabled: core.serialization.property("memory_enabled", core.serialization.boolean().optional()),
    memoryRetentionDays: core.serialization.property("memory_retention_days", core.serialization.number().optional()),
});

export declare namespace CreateAgentRequest {
    export interface Raw {
        name: string;
        slug?: string | null;
        prompt?: string | null;
        first_message?: string | null;
        language?: string | null;
        llm_model?: string | null;
        voice_id: string;
        temperature?: number | null;
        config?: Record<string, unknown> | null;
        is_public?: boolean | null;
        allowed_origins?: string[] | null;
        hostname_allowlist?: string[] | null;
        memory_enabled?: boolean | null;
        memory_retention_days?: number | null;
    }
}
