/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const MoveAgentTestRequest: core.serialization.Schema<
    serializers.tts.MoveAgentTestRequest.Raw,
    Speechify.tts.MoveAgentTestRequest
> = core.serialization.object({
    folderId: core.serialization.property("folder_id", core.serialization.string().optionalNullable()),
});

export declare namespace MoveAgentTestRequest {
    export interface Raw {
        folder_id?: (string | null) | null;
    }
}
