/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { EvaluationCriterion } from "../../../../types/EvaluationCriterion";
import { DataCollectionField } from "../../../../types/DataCollectionField";

export const UpdateEvaluationConfigRequest: core.serialization.Schema<
    serializers.tts.UpdateEvaluationConfigRequest.Raw,
    Speechify.tts.UpdateEvaluationConfigRequest
> = core.serialization.object({
    criteria: core.serialization.list(EvaluationCriterion),
    dataCollection: core.serialization.property("data_collection", core.serialization.list(DataCollectionField)),
});

export declare namespace UpdateEvaluationConfigRequest {
    export interface Raw {
        criteria: EvaluationCriterion.Raw[];
        data_collection: DataCollectionField.Raw[];
    }
}
