/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { UpdateAgentTestRequestConfig } from "../../types/UpdateAgentTestRequestConfig";
import { ToolMockConfig } from "../../../../types/ToolMockConfig";

export const UpdateAgentTestRequest: core.serialization.Schema<
    serializers.tts.UpdateAgentTestRequest.Raw,
    Speechify.tts.UpdateAgentTestRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    config: UpdateAgentTestRequestConfig.optional(),
    toolMockConfig: core.serialization.property("tool_mock_config", ToolMockConfig.optional()),
});

export declare namespace UpdateAgentTestRequest {
    export interface Raw {
        name?: string | null;
        description?: string | null;
        config?: UpdateAgentTestRequestConfig.Raw | null;
        tool_mock_config?: ToolMockConfig.Raw | null;
    }
}
