/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Speechify from "../../../../../api/index";
import * as core from "../../../../../core";
import { TestRunConfigOverride } from "../../../../types/TestRunConfigOverride";

export const RunAllTestsRequest: core.serialization.Schema<
    serializers.RunAllTestsRequest.Raw,
    Speechify.RunAllTestsRequest
> = core.serialization.object({
    configOverride: core.serialization.property("config_override", TestRunConfigOverride.optional()),
    flowVersionId: core.serialization.property("flow_version_id", core.serialization.string().optional()),
});

export declare namespace RunAllTestsRequest {
    export interface Raw {
        config_override?: TestRunConfigOverride.Raw | null;
        flow_version_id?: string | null;
    }
}
