/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Speechify from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateAgentRequestLlmProvider } from "../../types/UpdateAgentRequestLlmProvider";
import { WidgetConfig } from "../../../../types/WidgetConfig";
import { AmdConfig } from "../../../../types/AmdConfig";
import { UpdateAgentRequestBackgroundNoisePreset } from "../../types/UpdateAgentRequestBackgroundNoisePreset";
import { UpdateAgentRequestSttOverride } from "../../types/UpdateAgentRequestSttOverride";

export const UpdateAgentRequest: core.serialization.Schema<
    serializers.UpdateAgentRequest.Raw,
    Speechify.UpdateAgentRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    prompt: core.serialization.string().optional(),
    firstMessage: core.serialization.property("first_message", core.serialization.string().optional()),
    language: core.serialization.string().optional(),
    llmProvider: core.serialization.property("llm_provider", UpdateAgentRequestLlmProvider.optional()),
    llmModel: core.serialization.property("llm_model", core.serialization.string().optional()),
    llmBaseUrl: core.serialization.property("llm_base_url", core.serialization.string().optional()),
    llmApiKey: core.serialization.property("llm_api_key", core.serialization.string().optional()),
    llmExtraBody: core.serialization.property(
        "llm_extra_body",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    voiceId: core.serialization.property("voice_id", core.serialization.string().optional()),
    temperature: core.serialization.number().optional(),
    widgetConfig: core.serialization.property("widget_config", WidgetConfig.optional()),
    isPublic: core.serialization.property("is_public", core.serialization.boolean().optional()),
    allowedOrigins: core.serialization.property(
        "allowed_origins",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    hostnameAllowlist: core.serialization.property(
        "hostname_allowlist",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    memoryEnabled: core.serialization.property("memory_enabled", core.serialization.boolean().optional()),
    memoryRetentionDays: core.serialization.property("memory_retention_days", core.serialization.number().optional()),
    webhookUrl: core.serialization.property("webhook_url", core.serialization.string().optional()),
    webhookSecret: core.serialization.property("webhook_secret", core.serialization.string().optional()),
    amd: AmdConfig.optional(),
    saveAudioRecording: core.serialization.property("save_audio_recording", core.serialization.boolean().optional()),
    navigatorMode: core.serialization.property("navigator_mode", core.serialization.boolean().optional()),
    ivrMemoryEnabled: core.serialization.property("ivr_memory_enabled", core.serialization.boolean().optional()),
    ttsSpeakingRate: core.serialization.property("tts_speaking_rate", core.serialization.number().optionalNullable()),
    clearTtsSpeakingRate: core.serialization.property(
        "clear_tts_speaking_rate",
        core.serialization.boolean().optional(),
    ),
    ttsPlaybackRate: core.serialization.property("tts_playback_rate", core.serialization.number().optionalNullable()),
    clearTtsPlaybackRate: core.serialization.property(
        "clear_tts_playback_rate",
        core.serialization.boolean().optional(),
    ),
    responseDelaySeconds: core.serialization.property(
        "response_delay_seconds",
        core.serialization.number().optionalNullable(),
    ),
    clearResponseDelaySeconds: core.serialization.property(
        "clear_response_delay_seconds",
        core.serialization.boolean().optional(),
    ),
    inactivityTimeoutSeconds: core.serialization.property(
        "inactivity_timeout_seconds",
        core.serialization.number().optional(),
    ),
    backgroundNoisePreset: core.serialization.property(
        "background_noise_preset",
        UpdateAgentRequestBackgroundNoisePreset.optional(),
    ),
    backgroundNoiseVolume: core.serialization.property(
        "background_noise_volume",
        core.serialization.number().optional(),
    ),
    sttOverride: core.serialization.property("stt_override", UpdateAgentRequestSttOverride.optional()),
});

export declare namespace UpdateAgentRequest {
    export interface Raw {
        name?: string | null;
        prompt?: string | null;
        first_message?: string | null;
        language?: string | null;
        llm_provider?: UpdateAgentRequestLlmProvider.Raw | null;
        llm_model?: string | null;
        llm_base_url?: string | null;
        llm_api_key?: string | null;
        llm_extra_body?: Record<string, unknown> | null;
        voice_id?: string | null;
        temperature?: number | null;
        widget_config?: WidgetConfig.Raw | null;
        is_public?: boolean | null;
        allowed_origins?: string[] | null;
        hostname_allowlist?: string[] | null;
        memory_enabled?: boolean | null;
        memory_retention_days?: number | null;
        webhook_url?: string | null;
        webhook_secret?: string | null;
        amd?: AmdConfig.Raw | null;
        save_audio_recording?: boolean | null;
        navigator_mode?: boolean | null;
        ivr_memory_enabled?: boolean | null;
        tts_speaking_rate?: (number | null) | null;
        clear_tts_speaking_rate?: boolean | null;
        tts_playback_rate?: (number | null) | null;
        clear_tts_playback_rate?: boolean | null;
        response_delay_seconds?: (number | null) | null;
        clear_response_delay_seconds?: boolean | null;
        inactivity_timeout_seconds?: number | null;
        background_noise_preset?: UpdateAgentRequestBackgroundNoisePreset.Raw | null;
        background_noise_volume?: number | null;
        stt_override?: UpdateAgentRequestSttOverride.Raw | null;
    }
}
