/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { GetStreamRequestModel } from "../../types/GetStreamRequestModel";
import { GetStreamOptionsRequest } from "../../../../types/GetStreamOptionsRequest";

export const GetStreamRequest: core.serialization.Schema<
    serializers.tts.GetStreamRequest.Raw,
    Omit<Speechify.tts.GetStreamRequest, "accept">
> = core.serialization.object({
    input: core.serialization.string(),
    language: core.serialization.string().optional(),
    model: GetStreamRequestModel.optional(),
    options: GetStreamOptionsRequest.optional(),
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
});

export declare namespace GetStreamRequest {
    export interface Raw {
        input: string;
        language?: string | null;
        model?: GetStreamRequestModel.Raw | null;
        options?: GetStreamOptionsRequest.Raw | null;
        voice_id: string;
    }
}
