/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const RollbackFlowRequest: core.serialization.Schema<
    serializers.agent.RollbackFlowRequest.Raw,
    Speechify.agent.RollbackFlowRequest
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace RollbackFlowRequest {
    export interface Raw {
        version_id: string;
    }
}
