/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Speechify from "../../../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../../../serialization/index";
import * as errors from "../../../../../../errors/index";

export declare namespace Tools {
    export interface Options {
        environment?: core.Supplier<environments.SpeechifyEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Tools {
    constructor(protected readonly _options: Tools.Options = {}) {}

    /**
     * List tools in the caller's workspace, most recently updated
     * first. Cursor-paginated: omit `cursor` to fetch the first page.
     * Default page size is 50 and max is 200. Walk pages while
     * `has_more` is true.
     *
     * @param {Speechify.agent.ListToolsRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.tools.list()
     */
    public async list(
        request: Speechify.agent.ListToolsRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<core.Page<Speechify.Tool>> {
        const list = async (request: Speechify.agent.ListToolsRequest): Promise<Speechify.ListToolsResponse> => {
            const { cursor, limit } = request;
            const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
            if (cursor != null) {
                _queryParams["cursor"] = cursor;
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            const _response = await core.fetcher({
                url: urlJoin(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SpeechifyEnvironment.Default,
                    "v1/agents/tools",
                ),
                method: "GET",
                headers: {
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@speechify/api",
                    "X-Fern-SDK-Version": "1.0.2",
                    "User-Agent": "@speechify/api/1.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                    ...requestOptions?.headers,
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
            });
            if (_response.ok) {
                return serializers.ListToolsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Speechify.BadRequestError(_response.error.body);
                    case 401:
                        throw new Speechify.UnauthorizedError(_response.error.body);
                    default:
                        throw new errors.SpeechifyError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/tools.");
                case "unknown":
                    throw new errors.SpeechifyError({
                        message: _response.error.errorMessage,
                    });
            }
        };
        return new core.Pageable<Speechify.ListToolsResponse, Speechify.Tool>({
            response: await list(request),
            hasNextPage: (response) => response?.nextCursor != null,
            getItems: (response) => response?.tools ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * Create a tool. For webhook tools, the response includes the HMAC
     * `webhook_secret` exactly once — store it immediately; subsequent
     * reads return a masked placeholder.
     *
     * @param {Speechify.agent.CreateToolRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.tools.create({
     *         name: "lookup_order",
     *         description: "Fetch order details by order ID.",
     *         kind: "webhook",
     *         config: {
     *             url: "https://api.your-app.com/webhooks/lookup-order",
     *             method: "POST",
     *             timeoutMs: 5000,
     *             headers: {
     *                 "X-Org-ID": "acme"
     *             },
     *             params: [{
     *                     name: "order_id",
     *                     type: "string",
     *                     description: "Order ID",
     *                     required: true
     *                 }]
     *         }
     *     })
     *
     * @example
     *     await client.agent.tools.create({
     *         name: "navigate_to",
     *         description: "Scroll the page to a named section.",
     *         kind: "client",
     *         config: {
     *             timeoutMs: 4000,
     *             params: [{
     *                     name: "section",
     *                     type: "string",
     *                     description: "Section name",
     *                     required: true,
     *                     enum: ["pricing", "docs", "contact"]
     *                 }]
     *         }
     *     })
     */
    public async create(
        request: Speechify.agent.CreateToolRequest,
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.Tool> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/tools",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.CreateToolRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Tool.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling POST /v1/agents/tools.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieve a tool by ID. Webhook secrets are always masked here.
     *
     * @param {string} id
     * @param {Speechify.agent.GetToolsRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.tools.get("id")
     */
    public async get(
        id: string,
        request: Speechify.agent.GetToolsRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.Tool> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/tools/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Tool.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/tools/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete a tool. Agents that had it attached get a soft-detach.
     *
     * @param {string} id
     * @param {Speechify.agent.DeleteToolsRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.tools.delete("id")
     */
    public async delete(
        id: string,
        request: Speechify.agent.DeleteToolsRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/tools/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling DELETE /v1/agents/tools/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Update a tool. Tool kind is immutable — create a new tool to change it.
     *
     * @param {string} id
     * @param {Speechify.agent.UpdateToolRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.tools.update("id")
     */
    public async update(
        id: string,
        request: Speechify.agent.UpdateToolRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.Tool> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/tools/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.UpdateToolRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Tool.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling PATCH /v1/agents/tools/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * List the agents in the caller's workspace that currently have
     * this tool attached. Useful before deleting a tool, to surface
     * which agents will lose access. Soft-deleted agents are filtered
     * out. Bounded by the number of agents per workspace (tens), so
     * the response is not paginated.
     *
     * @param {string} id
     * @param {Speechify.agent.ListAttachedAgentsToolsRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.tools.listAttachedAgents("id")
     */
    public async listAttachedAgents(
        id: string,
        request: Speechify.agent.ListAttachedAgentsToolsRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.ListToolAttachedAgentsResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/tools/${encodeURIComponent(id)}/attached-agents`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.ListToolAttachedAgentsResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling GET /v1/agents/tools/{id}/attached-agents.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Rotate the HMAC signing secret on a webhook tool. The tool id
     * is preserved so attached agents keep working; only the secret
     * rolls. The new plaintext is returned on `webhook_secret`
     * exactly once — store it immediately, subsequent reads always
     * return the masked placeholder. The previous secret is
     * invalidated immediately on success.
     *
     * @param {string} id
     * @param {Speechify.agent.RotateSecretToolsRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.tools.rotateSecret("id")
     */
    public async rotateSecret(
        id: string,
        request: Speechify.agent.RotateSecretToolsRequest = {},
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.Tool> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/tools/${encodeURIComponent(id)}/rotate-secret`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.Tool.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling POST /v1/agents/tools/{id}/rotate-secret.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Read-only catalogue of every system builtin the worker knows
     * about. The console fetches this at runtime rather than
     * maintaining a parallel client-side list; the server
     * is the single source of truth for the label and description
     * copy a customer sees in the builtin-instance picker.
     *
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.tools.listSystemBuiltins()
     */
    public async listSystemBuiltins(
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.ListSystemBuiltinsResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/tools/system-builtins",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.ListSystemBuiltinsResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling GET /v1/agents/tools/system-builtins.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Probe a customer-supplied MCP server config without persisting
     * anything. The server opens the configured transport, runs the
     * `initialize` + `list_tools` handshake, and returns either the
     * discovered tool catalogue or a structured error string. Pass
     * `tool_id` from the edit-form flow when the auth payload carries
     * `_set` markers but no plaintext, so the server can hydrate the
     * stored secret from the encrypted column before probing.
     *
     * @param {Speechify.agent.TestMcpConnectionRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.tools.testMcpConnection({
     *         config: {
     *             endpoint: "endpoint",
     *             auth: {
     *                 type: "none"
     *             }
     *         }
     *     })
     */
    public async testMcpConnection(
        request: Speechify.agent.TestMcpConnectionRequest,
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.McpProbeResult> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/tools/test-mcp-connection",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.TestMcpConnectionRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.McpProbeResult.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling POST /v1/agents/tools/test-mcp-connection.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Probe a customer-supplied webhook tool config without persisting
     * anything. The server fires the exact request shape the worker
     * sends on a real invocation — same JSON body, same HMAC-SHA256
     * signature — with an empty argument set, and reports the
     * endpoint's status code, latency, and a truncated response body,
     * or a transport-level failure reason. The probe carries an
     * `X-Speechify-Webhook-Test: true` header so a careful endpoint
     * can recognise the test and skip its real side effect. Pass
     * `tool_id` from the edit-form flow so the server signs the probe
     * with the tool's stored HMAC secret.
     *
     * @param {Speechify.agent.TestWebhookConnectionRequest} request
     * @param {Tools.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.tools.testWebhookConnection({
     *         config: {
     *             url: "url"
     *         }
     *     })
     */
    public async testWebhookConnection(
        request: Speechify.agent.TestWebhookConnectionRequest,
        requestOptions?: Tools.RequestOptions,
    ): Promise<Speechify.WebhookProbeResult> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/tools/test-webhook-connection",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.TestWebhookConnectionRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.WebhookProbeResult.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling POST /v1/agents/tools/test-webhook-connection.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = (await core.Supplier.get(this._options.token)) ?? process?.env["SPEECHIFY_API_KEY"];
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
