/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model used for audio synthesis. `simba-english` is optimized for English, `simba-multilingual` for non-English or mixed input. `simba-3.0` is the streaming-native model with lower TTFB and richer expressivity. Currently English only; multilingual coming soon. Non-English voices return 400 until multilingual support ships.
 */
export type GetSpeechRequestModel =
    /**
     * simba-english is optimized for English words. */
    | "simba-english"
    /**
     * simba-multilingual is optimized for non-English words or mixed languages. */
    | "simba-multilingual"
    /**
     * simba-3.0 is the streaming-native model with lower TTFB and richer expressivity. Currently English only; multilingual coming soon. Non-English voices return 400 until multilingual support ships. */
    | "simba-3.0";
export const GetSpeechRequestModel = {
    SimbaEnglish: "simba-english",
    SimbaMultilingual: "simba-multilingual",
    Simba30: "simba-3.0",
} as const;
