/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../index";

/**
 * Replaces the test config when present.
 */
export type UpdateAgentTestRequestConfig =
    | Speechify.ReplyConfig
    | Speechify.ToolCallConfig
    | Speechify.SimulationConfig;
