/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface InvalidateIvrMenuRequest {
    /** Operator-debug cause string. Bounded to 256 chars. */
    reason?: string;
}
