/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListIvrMemoryRequest {
    /**
     * Optional SHA-256 fingerprint hash to narrow the list to one menu.
     */
    fingerprint?: string;
}
