/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { WebhookToolConfig } from "../../../../../../types/WebhookToolConfig";

export const TestWebhookConnectionRequest: core.serialization.Schema<
    serializers.agent.TestWebhookConnectionRequest.Raw,
    Speechify.agent.TestWebhookConnectionRequest
> = core.serialization.object({
    config: WebhookToolConfig,
    toolId: core.serialization.property("tool_id", core.serialization.string().optional()),
});

export declare namespace TestWebhookConnectionRequest {
    export interface Raw {
        config: WebhookToolConfig.Raw;
        tool_id?: string | null;
    }
}
