/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateKnowledgeBaseRequest: core.serialization.Schema<
    serializers.agent.CreateKnowledgeBaseRequest.Raw,
    Speechify.agent.CreateKnowledgeBaseRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
});

export declare namespace CreateKnowledgeBaseRequest {
    export interface Raw {
        name: string;
        description?: string | null;
    }
}
