/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateCrawlImportRequest: core.serialization.Schema<
    serializers.agent.CreateCrawlImportRequest.Raw,
    Speechify.agent.CreateCrawlImportRequest
> = core.serialization.object({
    url: core.serialization.string(),
    maxPages: core.serialization.property("max_pages", core.serialization.number().optional()),
    maxDepth: core.serialization.property("max_depth", core.serialization.number().optional()),
    folderId: core.serialization.property("folder_id", core.serialization.string().optionalNullable()),
});

export declare namespace CreateCrawlImportRequest {
    export interface Raw {
        url: string;
        max_pages?: number | null;
        max_depth?: number | null;
        folder_id?: (string | null) | null;
    }
}
