/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const UpdateKnowledgeBaseRequest: core.serialization.Schema<
    serializers.agent.UpdateKnowledgeBaseRequest.Raw,
    Speechify.agent.UpdateKnowledgeBaseRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace UpdateKnowledgeBaseRequest {
    export interface Raw {
        name?: string | null;
        description?: string | null;
    }
}
