/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional non-default streaming-STT stack for this agent.
 * Omit to use the worker's default stack (today: whisper-v3).
 * See the Agent schema for the full option semantics.
 */
export type CreateAgentRequestSttOverride = "flux" | "whisper-v3" | "gpt-realtime-whisper";
export const CreateAgentRequestSttOverride = {
    Flux: "flux",
    WhisperV3: "whisper-v3",
    GptRealtimeWhisper: "gpt-realtime-whisper",
} as const;
