/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * LLM backend. Send an empty string together with
 * `llm_model: ""` to clear the pair to the platform default
 * (today: Speechify Kimi K2.6). Sending one populated and
 * one empty is rejected as a 400. Omit both to leave the
 * stored pair unchanged. Switching to a non-`custom` provider
 * clears any stored `llm_base_url` / `llm_api_key` /
 * `llm_extra_body`.
 */
export type UpdateAgentRequestLlmProvider = "openai" | "speechify" | "custom" | "";
export const UpdateAgentRequestLlmProvider = {
    Openai: "openai",
    Speechify: "speechify",
    Custom: "custom",
    Empty: "",
} as const;
