/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Streaming-STT stack override. Send an empty string ("") to
 * clear the override and fall back to the worker default
 * (today: whisper-v3). Any non-empty value must be a known
 * stack name.
 */
export type UpdateAgentRequestSttOverride = "flux" | "whisper-v3" | "gpt-realtime-whisper" | "";
export const UpdateAgentRequestSttOverride = {
    Flux: "flux",
    WhisperV3: "whisper-v3",
    GptRealtimeWhisper: "gpt-realtime-whisper",
    Empty: "",
} as const;
