/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateFolderRequest {
    name: string;
    /**
     * Parent folder. Prefixed wire identifier
     * (`kfolder_<26 char Crockford base32>`); null/omitted creates a
     * root-level folder.
     */
    parentFolderId?: string | null;
}
