/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CreateSitemapImportRequest {
    url: string;
    /**
     * Folder to import the documents into. Prefixed wire identifier
     * (`kfolder_<26 char Crockford base32>`); null/omitted = root.
     */
    folderId?: string | null;
}
