/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface DeleteFolderKnowledgeBasesRequest {
    /**
     * When true, delete the folder even if it still contains documents or sub-folders; contents are moved to root.
     */
    force?: boolean;
}
