/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateRefreshConfigRequest {
    enabled?: boolean;
    intervalDays?: number;
    autoRemoveEnabled?: boolean;
}
