// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { AudioClient } from "../resources/audio/client/Client.js";
import { VoicesClient } from "../resources/voices/client/Client.js";

export declare namespace TtsClient {
    export type Options = BaseClientOptions;
}

export class TtsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TtsClient.Options>;
    protected _audio: AudioClient | undefined;
    protected _voices: VoicesClient | undefined;

    constructor(options: TtsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get audio(): AudioClient {
        return (this._audio ??= new AudioClient(this._options));
    }

    public get voices(): VoicesClient {
        return (this._voices ??= new VoicesClient(this._options));
    }
}
