/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Speechify from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { SystemToolConfig } from "../../../../../types/SystemToolConfig";
import { WebhookToolConfig } from "../../../../../types/WebhookToolConfig";
import { ClientToolConfig } from "../../../../../types/ClientToolConfig";
import { McpToolConfig } from "../../../../../types/McpToolConfig";

export const UpdateToolRequestConfig: core.serialization.Schema<
    serializers.agent.UpdateToolRequestConfig.Raw,
    Speechify.agent.UpdateToolRequestConfig
> = core.serialization.undiscriminatedUnion([SystemToolConfig, WebhookToolConfig, ClientToolConfig, McpToolConfig]);

export declare namespace UpdateToolRequestConfig {
    export type Raw = SystemToolConfig.Raw | WebhookToolConfig.Raw | ClientToolConfig.Raw | McpToolConfig.Raw;
}
