/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { AmdConfig } from "../../../../../../types/AmdConfig";

export const CreateOutboundCallRequest: core.serialization.Schema<
    serializers.agent.CreateOutboundCallRequest.Raw,
    Speechify.agent.CreateOutboundCallRequest
> = core.serialization.object({
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    to: core.serialization.string(),
    callerIdNumber: core.serialization.property("caller_id_number", core.serialization.string().optional()),
    dtmfPrefix: core.serialization.property("dtmf_prefix", core.serialization.string().optional()),
    dynamicVariables: core.serialization.property(
        "dynamic_variables",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    ringingTimeoutMs: core.serialization.property("ringing_timeout_ms", core.serialization.number().optional()),
    amd: AmdConfig.optional(),
});

export declare namespace CreateOutboundCallRequest {
    export interface Raw {
        agent_id: string;
        to: string;
        caller_id_number?: string | null;
        dtmf_prefix?: string | null;
        dynamic_variables?: Record<string, unknown> | null;
        ringing_timeout_ms?: number | null;
        amd?: AmdConfig.Raw | null;
    }
}
