/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         nodes: [{
 *                 "key": "value"
 *             }],
 *         edges: [{
 *                 "key": "value"
 *             }]
 *     }
 */
export interface PutFlowRequest {
    name?: string;
    notes?: string;
    nodes: Record<string, unknown>[];
    edges: Record<string, unknown>[];
    variables?: Record<string, unknown>[];
}
