/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         versionId: "9c1e8a40-3b2d-4f6a-8e11-2a7d5c9f0b34"
 *     }
 */
export interface RollbackFlowRequest {
    /** The flow version to roll back to. */
    versionId: string;
}
