/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * Type-specific configuration document.
 */
export type AgentTestConfig =
    | Speechify.tts.ScenarioConfig
    | Speechify.tts.ToolCallConfig
    | Speechify.tts.SimulationConfig;
