/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One entry in a batch-run request. Omit `agent_id` to fan out to
 * every agent the test is attached to.
 */
export interface BatchRunEntry {
    testId: string;
    agentId?: string;
}
