/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConversationTransport = "web" | "sip";
export const ConversationTransport = {
    Web: "web",
    Sip: "sip",
} as const;
