/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * A structured value the post-call evaluator should extract from the
 * transcript. `int` is distinct from `number` so downstream consumers
 * receive whole integers without a synthetic decimal.
 */
export interface DataCollectionField {
    key: string;
    description: string;
    type: Speechify.tts.DataCollectionFieldType;
}
