/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Three-state criterion result. `unknown` means the criterion did not apply to this call.
 */
export type EvaluationStatus = "success" | "failure" | "unknown";
export const EvaluationStatus = {
    Success: "success",
    Failure: "failure",
    Unknown: "unknown",
} as const;
