/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One LLM-scored assertion about the call ("Did the agent confirm the customer's name?").
 */
export interface EvaluationCriterion {
    id: string;
    name: string;
    description: string;
}
