/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The format of the audio data
 */
export type GetSpeechResponseAudioFormat = "wav" | "mp3" | "ogg" | "aac";
export const GetSpeechResponseAudioFormat = {
    Wav: "wav",
    Mp3: "mp3",
    Ogg: "ogg",
    Aac: "aac",
} as const;
