/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

export interface KnowledgeBaseDocument {
    id: string;
    kbId: string;
    filename: string;
    contentType: string;
    byteSize: number;
    charCount: number;
    chunkCount: number;
    status: Speechify.tts.KnowledgeBaseDocumentStatus;
    /** Populated when status is failed. */
    error?: string;
    createdAt: Date;
    updatedAt: Date;
}
