/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

export interface ListKnowledgeBaseDocumentsResponse {
    documents: Speechify.tts.KnowledgeBaseDocument[];
}
