/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * Workspace-wide paginated list of tests. `next_cursor` is the opaque
 * page cursor; omit on the first call, then pass through to get the
 * next page until the field is absent.
 */
export interface ListTestsResponse {
    tests: Speechify.tts.AgentTestWithLastRun[];
    nextCursor?: string;
}
