/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How a `ParameterCheck` validates a tool argument.
 * - `exact` - JSON equality.
 * - `regex` - the argument stringified is matched against the pattern.
 * - `llm` - an LLM judge decides whether the value semantically satisfies
 *   the criteria (e.g. "is a plausible email address").
 */
export type ParameterCheckMode = "exact" | "regex" | "llm";
export const ParameterCheckMode = {
    Exact: "exact",
    Regex: "regex",
    Llm: "llm",
} as const;
