/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * Response from `POST /v1/agents/{id}/tests/runs`. Contains every
 * newly-queued run so the client can poll each for completion.
 * Capped at 50 runs per call.
 */
export interface RunAgentTestsResponse {
    runs: Speechify.tts.AgentTestRun[];
}
