/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Result details for a `scenario` test run.
 */
export interface ScenarioResult {
    /** The raw text response the agent produced. */
    agentResponse: string;
    passed: boolean;
    /** LLM judge's explanation of the verdict. */
    rationale: string;
    /** 0-1 judge confidence score. */
    score: number;
    /** Wall-clock time for the run in milliseconds. */
    durationMs: number;
}
