/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * Result details for a `simulation` test run.
 */
export interface SimulationResult {
    /** Full synthetic conversation in order. */
    transcript: Speechify.tts.SimulationMessage[];
    /** Every tool invocation across all turns. */
    toolCalls?: Speechify.tts.SimulationToolCall[];
    /** Number of agent turns that ran before the simulation ended. */
    turnsUsed: number;
    passed: boolean;
    /** LLM judge's explanation of the verdict. */
    rationale: string;
    durationMs: number;
}
