/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * A workspace the caller belongs to.
 */
export interface Tenant {
    /** Opaque workspace ID. */
    id: string;
    /** Display name set by the workspace owner. */
    name: string;
    /** Billing plan tier. */
    plan: Speechify.tts.TenantPlan;
    /** Geographic region the workspace's data is pinned to. */
    dataRegion: Speechify.tts.TenantDataRegion;
    /** When true, HIPAA-compliant retention and logging is enforced. */
    hipaaMode: boolean;
    /** When true, no transcript / audio payloads are retained server-side. */
    zeroRetention: boolean;
    createdAt: Date;
    updatedAt: Date;
}
