/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Billing plan tier.
 */
export type TenantPlan = "free" | "pro" | "business" | "enterprise";
export const TenantPlan = {
    Free: "free",
    Pro: "pro",
    Business: "business",
    Enterprise: "enterprise",
} as const;
