/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A canned response returned when the agent calls `tool_name`. If
 * `args_match` is set the mock only triggers when its value appears
 * as a substring of the JSON-serialised call arguments (a deliberately
 * simple v1 matcher — full expression support is planned). A mock
 * without `args_match` always matches for its tool.
 */
export interface ToolMock {
    /** Name of the tool to intercept. */
    toolName: string;
    /**
     * Optional substring of the JSON-serialised call arguments. When
     * absent the mock matches unconditionally for this tool.
     */
    argsMatch?: string;
    response?: unknown;
}
