/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * One of `SystemToolConfig`, `WebhookToolConfig`, or `ClientToolConfig` depending on `kind`.
 */
export type ToolConfig =
    | Speechify.tts.SystemToolConfig
    | Speechify.tts.WebhookToolConfig
    | Speechify.tts.ClientToolConfig;
