/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

export interface Tool {
    id: string;
    name: string;
    description: string;
    kind: Speechify.tts.ToolKind;
    /** One of `SystemToolConfig`, `WebhookToolConfig`, or `ClientToolConfig` depending on `kind`. */
    config: Speechify.tts.ToolConfig;
    /**
     * HMAC signing secret for `kind=webhook`. Returned in full **only** on the create
     * response; all subsequent reads return a masked placeholder. Store it on first
     * create — there is no way to retrieve it later.
     */
    webhookSecret?: string;
    createdAt: Date;
    updatedAt: Date;
}
