/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../index";

/**
 * Config shape for `kind=webhook`.
 */
export interface WebhookToolConfig {
    url: string;
    method?: Speechify.tts.WebhookToolConfigMethod;
    /** Static headers sent with every call. `Authorization` and `X-Speechify-Signature` are reserved. */
    headers?: Record<string, string>;
    /** Per-call timeout in milliseconds. */
    timeoutMs?: number;
    params?: Speechify.tts.ToolParam[];
}
