/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Speechify from "../../../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../../../serialization/index";
import * as errors from "../../../../../../errors/index";

export declare namespace SipTrunks {
    export interface Options {
        environment?: core.Supplier<environments.SpeechifyEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class SipTrunks {
    constructor(protected readonly _options: SipTrunks.Options = {}) {}

    /**
     * List all SIP trunks in the caller's workspace.
     *
     * @param {SipTrunks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     *
     * @example
     *     await client.agent.sipTrunks.list()
     */
    public async list(requestOptions?: SipTrunks.RequestOptions): Promise<Speechify.ListSipTrunksResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/sip-trunks",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.ListSipTrunksResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/sip-trunks.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Create a SIP trunk. For `kind=byoc` supply `sip_address` plus
     * optional digest credentials and IP allowlist. For `kind=twilio`
     * use `ImportPhoneNumber` with a `twilio` spec instead - trunk
     * creation is handled automatically. Returns 402 when the workspace
     * has reached the 20-trunk cap.
     *
     * @param {Speechify.agent.CreateSipTrunkRequest} request
     * @param {SipTrunks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.PaymentRequiredError}
     *
     * @example
     *     await client.agent.sipTrunks.create({
     *         name: "Telnyx BYOC",
     *         kind: "byoc",
     *         direction: "both",
     *         sipAddress: "sip.telnyx.com",
     *         authUsername: "myuser",
     *         authPassword: "mypassword",
     *         transport: "auto",
     *         mediaEncryption: "allow"
     *     })
     */
    public async create(
        request: Speechify.agent.CreateSipTrunkRequest,
        requestOptions?: SipTrunks.RequestOptions,
    ): Promise<Speechify.SipTrunk> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                "v1/agents/sip-trunks",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.CreateSipTrunkRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.SipTrunk.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 402:
                    throw new Speechify.PaymentRequiredError(
                        serializers.Error_.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                    );
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling POST /v1/agents/sip-trunks.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieve a SIP trunk by ID.
     *
     * @param {string} id
     * @param {Speechify.agent.GetSipTrunksRequest} request
     * @param {SipTrunks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.sipTrunks.get("id")
     */
    public async get(
        id: string,
        request: Speechify.agent.GetSipTrunksRequest = {},
        requestOptions?: SipTrunks.RequestOptions,
    ): Promise<Speechify.SipTrunk> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/sip-trunks/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.SipTrunk.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/sip-trunks/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Delete a SIP trunk. This also removes the backing LiveKit inbound
     * trunk, outbound trunk, and dispatch rule if they were provisioned
     * by us. Phone numbers attached to this trunk are left in place but
     * become non-functional until rebound to a new trunk.
     *
     * @param {string} id
     * @param {Speechify.agent.DeleteSipTrunksRequest} request
     * @param {SipTrunks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.UnauthorizedError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.sipTrunks.delete("id")
     */
    public async delete(
        id: string,
        request: Speechify.agent.DeleteSipTrunksRequest = {},
        requestOptions?: SipTrunks.RequestOptions,
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/sip-trunks/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Speechify.UnauthorizedError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/agents/sip-trunks/{id}.",
                );
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = (await core.Supplier.get(this._options.token)) ?? process?.env["SPEECHIFY_API_KEY"];
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
