/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         e164: "+14155552671",
 *         label: "Sales line",
 *         agentId: "agent_01HS..."
 *     }
 */
export interface PurchasePhoneNumberRequest {
    /** The E.164 number to buy. Must currently be in carrier inventory. */
    e164: string;
    /** Optional human-readable label. */
    label?: string;
    /**
     * Optional agent to bind the number to at purchase time.
     * Prefixed wire identifier (`agent_<26 char Crockford base32>`).
     */
    agentId?: string;
}
