/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetTestStatsTestsRequest {
    /**
     * Trailing window in days (default 30, max 90).
     */
    windowDays?: number;
}
