/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListAllTestsTestsRequest {
    /**
     * Comma-separated agent IDs to filter on.
     */
    agentId?: string;
    /**
     * Comma-separated test types (reply|tool|simulation).
     */
    type?: string;
    /**
     * Comma-separated last-run statuses.
     */
    status?: string;
    /**
     * Folder ID to filter on, or "root" for unfiled tests.
     */
    folderId?: string;
    /**
     * Only return tests updated after this RFC3339 timestamp.
     */
    updatedAfter?: string;
    /**
     * Substring match on name or description.
     */
    q?: string;
    /**
     * Max tests per page (default 50, max 200).
     */
    limit?: number;
    /**
     * Opaque pagination cursor from a previous response.
     */
    cursor?: string;
}
