/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         entries: [{
 *                 testId: "test_01ky612y9cb7dbaj638x46msxv"
 *             }]
 *     }
 */
export interface RunBatchRequest {
    entries: Speechify.BatchRunEntry[];
}
