/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateAgentTestFolderRequest {
    name?: string;
    /**
     * Prefixed wire identifier (`folder_<26 char Crockford base32>`)
     * of the folder to reparent this folder under.
     */
    parentFolderId?: string;
    /**
     * When `true`, reparents this folder to root (clears
     * `parent_folder_id`). Wins over `parent_folder_id` when
     * both are sent.
     */
    clearParentFolderId?: boolean;
}
