/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Speechify from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ReplyConfig } from "../../../../../types/ReplyConfig";
import { ToolCallConfig } from "../../../../../types/ToolCallConfig";
import { SimulationConfig } from "../../../../../types/SimulationConfig";

export const UpdateAgentTestRequestConfig: core.serialization.Schema<
    serializers.agent.UpdateAgentTestRequestConfig.Raw,
    Speechify.agent.UpdateAgentTestRequestConfig
> = core.serialization.undiscriminatedUnion([ReplyConfig, ToolCallConfig, SimulationConfig]);

export declare namespace UpdateAgentTestRequestConfig {
    export type Raw = ReplyConfig.Raw | ToolCallConfig.Raw | SimulationConfig.Raw;
}
