/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Gender marker for the personal voice
 * male GenderMale
 * female GenderFemale
 * notSpecified GenderNotSpecified
 */
export type VoicesCreateRequestGender = "male" | "female" | "notSpecified";
export const VoicesCreateRequestGender = {
    Male: "male",
    Female: "female",
    NotSpecified: "notSpecified",
} as const;
