/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const UpdateIvrMenuLabelRequest: core.serialization.Schema<
    serializers.agent.UpdateIvrMenuLabelRequest.Raw,
    Speechify.agent.UpdateIvrMenuLabelRequest
> = core.serialization.object({
    dtmf: core.serialization.string(),
    label: core.serialization.string(),
});

export declare namespace UpdateIvrMenuLabelRequest {
    export interface Raw {
        dtmf: string;
        label: string;
    }
}
