/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         grantType: "client_credentials"
 *     }
 */
export interface CreateAccessTokenRequest {
    /** in: body */
    grantType: Speechify.tts.CreateAccessTokenRequestGrantType;
    /**
     * The scope, or a space-delimited list of scopes the token is requested for
     * in: body
     */
    scope?: Speechify.tts.CreateAccessTokenRequestScope;
}
