/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One organisational node in the per-owner tests tree.
 */
export interface AgentTestFolder {
    /**
     * Prefixed wire identifier (`folder_<26 char Crockford base32>`).
     * URL paths accept only this
     * prefixed form; legacy UUID path parameters are rejected with
     * 404.
     */
    id: string;
    /**
     * When set, prefixed wire identifier
     * (`folder_<26 char Crockford base32>`) of the parent folder.
     * Null means root.
     */
    parentFolderId?: string | null;
    name: string;
    createdAt: Date;
    updatedAt: Date;
}
