/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * A suite run plus every child run, for the grouped detail view.
 */
export interface AgentTestSuiteRunWithRuns extends Speechify.AgentTestSuiteRun {
    runs: Speechify.SuiteChildRun[];
}
