/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional override for the streaming-STT stack this agent
 * dispatches with. Null means use the worker's default
 * stack (today: whisper-v3, Baseten Whisper Large V3). Pick
 * `whisper-v3` to pin Whisper Large V3 explicitly, `flux` to
 * opt into Deepgram Flux's semantic end-of-turn detection, or
 * `gpt-realtime-whisper` for OpenAI's streaming Whisper-class
 * STT.
 */
export type AgentSttOverride = "flux" | "whisper-v3" | "gpt-realtime-whisper";
export const AgentSttOverride = {
    Flux: "flux",
    WhisperV3: "whisper-v3",
    GptRealtimeWhisper: "gpt-realtime-whisper",
} as const;
