/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentVoiceLanguage {
    /** BCP-47-ish locale tag (e.g. `en-US`, `de-DE`). */
    locale: string;
    /**
     * URL to a short audio preview for this locale, or null if
     * no preview is available.
     */
    previewAudio: string | null;
}
