/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Voice provenance. Always `shared` on this endpoint — personal
 * / cloned voices are not exposed here; they stay on
 * `GET /v1/voices`.
 */
export type AgentVoiceType = "shared";
export const AgentVoiceType = {
    Shared: "shared",
} as const;
