/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Bare list of the tools attached to an agent. Not paginated —
 * an agent's tool attachment count is bounded by configuration,
 * not by data scale.
 */
export interface AttachedToolsResponse {
    tools: Speechify.Tool[];
}
