// This file was auto-generated by Fern from our API Definition.

/** Audio output format for the streaming endpoint (`POST /v1/audio/stream`), as a `codec_sampleRate_bitrate` string. Same as `AudioOutputFormat` minus the `wav_*` formats: wav is only available on `POST /v1/audio/speech`. `pcm_*` and `ulaw_8000` are headerless raw audio; `pcm_16000` and `ulaw_8000` are the telephony formats Twilio/LiveKit SIP expect. */
export const AudioStreamOutputFormat = {
    Pcm8000: "pcm_8000",
    Pcm16000: "pcm_16000",
    Pcm22050: "pcm_22050",
    Pcm24000: "pcm_24000",
    Pcm44100: "pcm_44100",
    Pcm48000: "pcm_48000",
    Mp32205032: "mp3_22050_32",
    Mp32205064: "mp3_22050_64",
    Mp32205096: "mp3_22050_96",
    Mp322050128: "mp3_22050_128",
    Mp322050192: "mp3_22050_192",
    Mp32400032: "mp3_24000_32",
    Mp32400064: "mp3_24000_64",
    Mp32400096: "mp3_24000_96",
    Mp324000128: "mp3_24000_128",
    Mp324000192: "mp3_24000_192",
    Ulaw8000: "ulaw_8000",
    Ogg24000: "ogg_24000",
    Aac24000: "aac_24000",
} as const;
export type AudioStreamOutputFormat = (typeof AudioStreamOutputFormat)[keyof typeof AudioStreamOutputFormat];
