/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * HTTP Basic auth — username + password.
 */
export interface BasicAuthConfig {
    username: string;
    password: string;
}
