/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * One recipient row in a batch call.
 */
export interface BatchRecipient {
    id: string;
    /**
     * Prefixed wire identifier (`batch_<26 char Crockford base32>`)
     * of the parent batch.
     */
    batchId: string;
    /** Recipient phone number in E.164 format. */
    phone: string;
    /** Per-recipient variable overrides injected into the agent prompt. */
    dynamicVars?: Record<string, unknown>;
    status: Speechify.BatchRecipientStatus;
    /**
     * Set once the call is placed. Prefixed wire identifier
     * (`conv_<26 char Crockford base32>`).
     */
    conversationId?: string | null;
    /** Populated when this recipient fails. */
    error?: string;
    attemptedAt?: Date | null;
    completedAt?: Date | null;
}
