/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One entry in a batch-run request. Omit `agent_id` to fan out to
 * every agent the test is attached to.
 */
export interface BatchRunEntry {
    /**
     * Prefixed wire identifier (`test_<26 char Crockford base32>`)
     * of the test to run.
     */
    testId: string;
    /**
     * Prefixed wire identifier (`agent_<26 char Crockford base32>`)
     * of the agent to run the test against. Omit to fan out to
     * every agent the test is attached to.
     */
    agentId?: string;
}
