/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A static bearer token sent as `Authorization: Bearer …`. For
 * rotating tokens prefer one of the oauth2 kinds.
 */
export interface BearerAuthConfig {
    token: string;
}
