/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Customer-facing per-tier limits + feature flags. The server-internal
 * HTTP rate/concurrency guards are deliberately omitted. Numeric fields are
 * caps; booleans gate features.
 */
export interface BillingEntitlements {
    /** Speechify-managed (purchased) phone numbers allowed. */
    phoneNumberQuota: number;
    /** Simultaneously-active voice calls allowed. */
    concurrentCallCap: number;
    /** Members allowed in a single workspace (owner + invitees). */
    maxMembers: number;
    /** Per-call wall-clock ceiling, in seconds. */
    maxCallDurationSeconds: number;
    /** Whether the workspace may create ADDITIONAL workspaces. */
    canCreateWorkspaces: boolean;
    /** Whether prepaid funds may be added beyond the monthly grant. */
    topupAllowed: boolean;
    /** Whether voice cloning is available. */
    voiceCloning: boolean;
    /** Whether batch outbound calls are available. */
    batchCalls: boolean;
}
