/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Canonical code the worker emits when the IVR
 * navigator gave up. NULL when the navigator completed
 * cleanly OR never started a plan.
 * * `no_goal` - the goal extractor returned empty.
 * * `no_cached_menu` - AMD-time cache miss for the root fingerprint.
 * * `below_threshold` - cached menu loaded but confidence < threshold.
 * * `fingerprint_mismatch` - in-call prompt diverged from the cached menu fingerprint.
 * * `goal_ambiguous` - cached options matched the goal more than once or not at all.
 * * `child_cache_miss` - sub-menu fingerprint had no cached row.
 * * `dtmf_send_failure` - DTMF press could not be delivered.
 * * `matched_option_missing_dtmf` - defensive shape guard.
 * * `disabled` - per-agent toggle off OR operator kill switch on.
 * * `repeated_prompt_max_retries` - bounded press-retry on the same fingerprint hit its cap of 1.
 */
export type ConversationIvrSurrenderReason =
    | "no_goal"
    | "no_cached_menu"
    | "below_threshold"
    | "fingerprint_mismatch"
    | "goal_ambiguous"
    | "child_cache_miss"
    | "dtmf_send_failure"
    | "matched_option_missing_dtmf"
    | "disabled"
    | "repeated_prompt_max_retries";
export const ConversationIvrSurrenderReason = {
    NoGoal: "no_goal",
    NoCachedMenu: "no_cached_menu",
    BelowThreshold: "below_threshold",
    FingerprintMismatch: "fingerprint_mismatch",
    GoalAmbiguous: "goal_ambiguous",
    ChildCacheMiss: "child_cache_miss",
    DtmfSendFailure: "dtmf_send_failure",
    MatchedOptionMissingDtmf: "matched_option_missing_dtmf",
    Disabled: "disabled",
    RepeatedPromptMaxRetries: "repeated_prompt_max_retries",
} as const;
