/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Returned synchronously when LiveKit accepts the SIP INVITE. Poll
 * `GET /v1/agents/conversations/{conversation_id}` for status transitions:
 * `pending` (ringing) → `active` (answered) → `completed`.
 */
export interface CreateOutboundCallResponse {
    /** ID of the conversation created for this call. Use to poll status. */
    conversationId: string;
    /** LiveKit room name the answered call joins. */
    room: string;
    /** LiveKit participant ID for the outbound SIP call leg. */
    sipParticipantId: string;
}
