/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreatedVoiceType = "shared" | "personal";
export const CreatedVoiceType = {
    Shared: "shared",
    Personal: "personal",
} as const;
