/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Request body for creating (POST) or replacing (PATCH) a flow
 * template. PATCH replaces the whole template, it is not a
 * field-by-field patch.
 */
export interface CreateFlowTemplateRequest {
    key: string;
    name: string;
    description?: string;
    /** Defaults to "custom" when omitted. */
    category?: string;
    graph: Speechify.FlowGraphInput;
}
