/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Three-state result the post-call evaluator emits per criterion.
 * `unknown` means the criterion did not apply to this call.
 */
export type CriterionStatus = "success" | "failure" | "unknown";
export const CriterionStatus = {
    Success: "success",
    Failure: "failure",
    Unknown: "unknown",
} as const;
