/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Declared type of a customer-scope variable. Enforced at save time
 * and again at session-start when an override value is supplied.
 * - `string`  - plain text value; interpolated verbatim with `{{name}}`
 * - `number`  - numeric value; rendered as its decimal representation
 * - `boolean` - `true` or `false`
 * - `json`    - any valid JSON value; use `{{name|json}}` to inject
 *               safely inside JSON tool bodies
 */
export type DynamicVariableType = "string" | "number" | "boolean" | "json";
export const DynamicVariableType = {
    String: "string",
    Number: "number",
    Boolean: "boolean",
    Json: "json",
} as const;
