// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface ErrorDetail {
    code: Speechify.ErrorCode;
    /**
     * Human-readable explanation of this specific occurrence.
     * Safe to surface in UI banners or pass to support. The
     * wording can change between releases; clients should
     * match on `code`, not on the message string.
     */
    message: string;
    /**
     * Per-field validation errors as `path -> message`. Only
     * present on 400 responses caused by request validation
     * (typically code=`validation_failed`). Keys are field
     * paths in dotted/bracket notation; values are short
     * human explanations safe to inline-surface next to the
     * offending form field.
     */
    fields?: Record<string, string> | undefined;
}
