/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * 400 body for flow save / publish / template operations. The standard
 * `Error` envelope (so clients read `error.code` = `validation_failed`
 * and `request_id`) plus the per-issue `issues` array the flow editor
 * uses for node highlighting and the Validator-tab list. `issues` is
 * absent on a plain bad request (e.g. an undecodable body, code
 * `bad_request`).
 */
export interface FlowValidationError {
    error: Speechify.ErrorDetail;
    requestId?: string;
    issues?: Speechify.FlowValidationIssue[];
}
