/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Single-resource envelope used by GET / PATCH /v1/agents/callers/{id}.
 */
export interface GetCallerResponse {
    caller: Speechify.Caller;
}
