// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

export interface GetSpeechResponse {
    /** Synthesized speech audio, Base64-encoded */
    audio_data: string;
    /** The format of the audio data */
    audio_format: GetSpeechResponse.AudioFormat;
    /** The number of billable characters processed in the request. */
    billable_characters_count: number;
    speech_marks: Speechify.SpeechMarks;
}

export namespace GetSpeechResponse {
    /** The format of the audio data */
    export const AudioFormat = {
        Wav: "wav",
        Mp3: "mp3",
        Ogg: "ogg",
        Aac: "aac",
        Pcm: "pcm",
    } as const;
    export type AudioFormat = (typeof AudioFormat)[keyof typeof AudioFormat];
}
