/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetVoicesModelName = "simba-english" | "simba-multilingual" | "simba-3.0";
export const GetVoicesModelName = {
    SimbaEnglish: "simba-english",
    SimbaMultilingual: "simba-multilingual",
    Simba30: "simba-3.0",
} as const;
