/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

export interface GetVoicesModel {
    languages: Speechify.GetVoiceLanguage[];
    name: Speechify.GetVoicesModelName;
}
