/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Wrapper returned by the async import endpoints (sitemap, crawl, multi-URL).
 */
export interface ImportJobResponse {
    job: Speechify.ImportJob;
}
