/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Unauthenticated preview of a workspace invite. Surfaces only what
 * the recipient needs to decide whether to accept (workspace name,
 * invited address, inviter, expiry). Billing, plan, data region,
 * and invite token are deliberately omitted.
 */
export interface InvitePreview {
    /** Opaque workspace id. Safe to echo back on the accept call. */
    tenantId: string;
    /** Workspace display name. */
    tenantName: string;
    /** The email address the inviter typed when creating the invite. */
    invitedEmail: string;
    /**
     * Firebase email of the member who created the invite. May be
     * absent if the Firebase profile lookup failed transiently —
     * clients should still render the preview in that case.
     */
    invitedByEmail?: string;
    /** Firebase display name of the member who created the invite. */
    invitedByDisplayName?: string;
    expiresAt: Date;
}
