/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One memorized IVR menu level. Identified by the
 * SHA-256 fingerprint of the normalized greeting transcript;
 * scoped to the caller's workspace (foreign-tenant menus are
 * never returned).
 *
 * `menu_tree` is the validated JSONB blob the worker consumes:
 * prompt text plus the options offered (label + DTMF). Sub-menus
 * reached by pressing an option are their own rows, looked up at
 * descent time by a fresh fingerprint - the tree structure is the
 * implicit graph of fingerprint -> fingerprint transitions.
 *
 * `confidence_score` is `succeeded_traversals / total_traversals`.
 * The worker's plan-then-execute fast path only activates at or
 * above 0.5.
 *
 * `invalidated_at` is non-null on a soft-deleted row; the API
 * filters these out of list / lookup / get responses so this field
 * is informational only.
 */
export interface IvrMenu {
    /**
     * Prefixed wire identifier (`menu_<26 char Crockford base32>`).
     * URL paths accept only this
     * prefixed form; legacy UUID path parameters are rejected with
     * 404.
     */
    id: string;
    fingerprintId: string;
    /** Null on the cross-tenant promoted slot. */
    tenantId?: string | null;
    schemaVersion: number;
    /** Validated menu_tree per contracts/agents/ivr_menu.schema.json. Opaque to consumers other than the worker. */
    menuTree: Record<string, unknown>;
    confidenceScore: number;
    succeededTraversals: number;
    totalTraversals: number;
    lastValidatedAt: Date;
    invalidatedAt?: Date | null;
    createdAt: Date;
    updatedAt: Date;
}
