// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../index.js";

/**
 * Payload for `GET /v1/voices` - the shared voice catalog plus the
 * workspace's personal cloned voices. Carries the shared pagination
 * metadata so the list can be paged when `limit` is supplied;
 * `next_cursor` is null and `has_more` is false when the full
 * catalogue is returned in one response.
 */
export interface ListVoicesResponse extends Speechify.PaginationMeta {
    voices: Speechify.GetVoice[];
}
