/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Response for `GET /v1/agents/sip-trunks`.
 */
export interface ListSipTrunksResponse {
    /** SIP trunks in the workspace (up to 20). */
    trunks: Speechify.SipTrunk[];
}
