/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Workspace-wide paginated list of tests. Walk pages while
 * `has_more` is true; pass `next_cursor` back as the request
 * `cursor` parameter.
 */
export interface ListTestsResponse extends Speechify.PaginationMeta {
    tests: Speechify.AgentTestWithLastRun[];
}
