/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Response for `GET /v1/agents/{id}/variables`. Returns both the
 * customer-scope variable catalogue and the read-only `system__*`
 * catalogue so the editor UI has a single source of truth.
 */
export interface ListDynamicVariablesResponse {
    /** Customer-defined variables for this agent. */
    variables: Speechify.DynamicVariable[];
    /**
     * Platform-populated `system__*` variables, provided for
     * reference. This list is the same for every agent.
     */
    systemVariables: Speechify.SystemVariableDoc[];
}
