/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Payload for GET /v1/agents/conversations/recent-callees.
 */
export interface ListRecentCalleesResponse extends Speechify.PaginationMeta {
    callees: Speechify.RecentCallee[];
}
