/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Response for `GET /v1/agents/phone-numbers`.
 */
export interface ListPhoneNumbersResponse {
    /** Phone numbers in the workspace (up to 100). */
    numbers: Speechify.PhoneNumber[];
}
