/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Config shape for `kind=mcp`. The worker opens the
 * configured transport at session start, runs `initialize` +
 * `list_tools`, and registers each discovered remote tool as a
 * livekit-agents function_tool proxying through the long-lived
 * ClientSession.
 */
export interface McpToolConfig {
    endpoint: string;
    transport?: Speechify.McpTransport;
    auth: Speechify.McpAuth;
}
