/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Member's role within the workspace.
 *
 * - `owner`  - Full control, including deleting the workspace.
 * - `admin`  - Manage members and invites; cannot change roles.
 * - `member` - Standard access, no administrative rights.
 */
export type MemberRole = "owner" | "admin" | "member";
export const MemberRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
} as const;
