/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Controls which tool calls the runner intercepts during a run.
 * System tools (`end_call`, `transfer_to_number`, etc.) are never
 * mocked regardless of strategy.
 * - `none` - no interception; all tools are called normally.
 * - `all` - every non-system tool call is intercepted and matched
 *   against the `mocks` list.
 * - `selected` - only tools explicitly listed in `mocks` are
 *   intercepted; others are called normally.
 */
export type MockingStrategy = "none" | "all" | "selected";
export const MockingStrategy = {
    None: "none",
    All: "all",
    Selected: "selected",
} as const;
