/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Static client_id + client_secret pair for the OAuth2
 * client-credentials flow. The tool runtime mints an access token
 * at request time and caches it per credential id.
 */
export interface OAuth2ClientCredentialsConfig {
    tokenUrl: string;
    clientId: string;
    clientSecret: string;
    scopes?: string[];
    audience?: string;
}
