/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Response from `POST /v1/agents/{id}/tests/runs` and the suite-run
 * resubmit endpoint. Contains every newly-queued run so the client
 * can poll each for completion, plus the `suite_run` that groups
 * them. `suite_run` is null only when a Run All found no tests.
 */
export interface RunAgentTestsResponse {
    runs: Speechify.AgentTestRun[];
    /** The suite run grouping the queued runs. */
    suiteRun?: Speechify.AgentTestSuiteRun | null;
}
