/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * One turn in a simulation conversation. `role` is `user` (the AI caller) or `assistant` (the agent).
 */
export interface SimulationMessage {
    role: Speechify.SimulationMessageRole;
    content: string;
}
