/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Three-state outcome. `unknown` means the criterion did not
 * apply on this run (the topic never came up); `failure`
 * means it did apply and the agent did not satisfy it.
 */
export type SimulationCriterionResultStatus = "success" | "failure" | "unknown";
export const SimulationCriterionResultStatus = {
    Success: "success",
    Failure: "failure",
    Unknown: "unknown",
} as const;
