/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One tool invocation that occurred during a simulation run.
 * `mocked` is true when the call was intercepted by the run's
 * mock config; false when the real tool was called or when the
 * tool is a system tool.
 */
export interface SimulationToolCall {
    /** Zero-based index of the conversation turn in which this call occurred. */
    turnIndex: number;
    toolName: string;
    args?: unknown;
    /** Response returned to the agent (absent for system tools that end the call). */
    response?: unknown;
    mocked: boolean;
}
