/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Configuration for a `simulation` test. An AI caller drives a
 * multi-turn conversation with the agent according to `scenario`.
 * After `max_turns` exchanges (or when the agent ends the call),
 * the unified post-call evaluator scores the synthetic transcript
 * against the agent's configured evaluation criteria + data
 * collection fields. A test passes when no configured criterion
 * fails and every `data_assertions` entry passes.
 */
export interface SimulationConfig {
    /** Instructions for the AI caller describing who they are and what they want. */
    scenario: string;
    /** Maximum agent turns before the simulation is cut off and judged. */
    maxTurns?: number;
    /** Optional seed conversation that precedes the AI caller's first generated message. */
    initialChatHistory?: Speechify.SimulationMessage[];
    /**
     * Optional assertions on the LLM-extracted data-collection
     * map. Each entry references a key from the agent's
     * data_collection config and validates the extracted value.
     * The test fails if any assertion fails.
     */
    dataAssertions?: Speechify.DataAssertion[];
    /**
     * Deprecated. Prefer the run-level `config_override`
     * on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
     * run-level override wins when both are set. Replaces the
     * agent's system prompt for this run only.
     */
    systemPromptOverride?: string;
    /**
     * Deprecated. Prefer the run-level `config_override`
     * on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
     * run-level override wins when both are set. Overrides the LLM
     * model used by the agent for this run only.
     */
    modelOverride?: string;
}
