/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SRTP media encryption policy.
 *
 * - `disable` - Unencrypted media only.
 * - `allow` - Negotiate SRTP; fall back to unencrypted. Recommended default.
 * - `require` - Reject calls that do not support SRTP.
 */
export type SipMediaEncryption = "disable" | "allow" | "require";
export const SipMediaEncryption = {
    Disable: "disable",
    Allow: "allow",
    Require: "require",
} as const;
