/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Where the trunk came from. Informs the provisioning path and
 * portability story.
 *
 * - `livekit` - Provisioned by LiveKit's native phone-number API.
 * - `twilio` - Backed by a Twilio Elastic SIP Trunk on the customer's account.
 * - `byoc` - Any SIP provider with a customer-managed trunk.
 */
export type SipTrunkKind = "livekit" | "twilio" | "byoc";
export const SipTrunkKind = {
    Livekit: "livekit",
    Twilio: "twilio",
    Byoc: "byoc",
} as const;
