/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the trunk handles inbound calls, outbound calls, or both.
 * A `both` trunk has distinct LiveKit inbound and outbound trunk IDs.
 */
export type SipTrunkDirection = "inbound" | "outbound" | "both";
export const SipTrunkDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
    Both: "both",
} as const;
