/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * A SIP trunk in the workspace. Trunks back one or more phone numbers
 * and hold the carrier credentials LiveKit uses to route calls.
 * `auth_password` is never echoed - `auth_password_set` indicates
 * whether one is configured.
 */
export interface SipTrunk {
    /**
     * Prefixed wire identifier (`trunk_<26 char Crockford base32>`).
     * URL paths accept only this
     * prefixed form; legacy UUID path parameters are rejected with
     * 404.
     */
    id: string;
    /** Human-readable name. */
    name: string;
    kind: Speechify.SipTrunkKind;
    direction: Speechify.SipTrunkDirection;
    /** LiveKit's inbound trunk ID (present when direction is `inbound` or `both`). */
    livekitInboundTrunkId?: string;
    /** LiveKit's outbound trunk ID (present when direction is `outbound` or `both`). */
    livekitOutboundTrunkId?: string;
    /** LiveKit dispatch rule ID that routes inbound calls into rooms. */
    livekitDispatchRuleId?: string;
    /** SIP endpoint hostname (e.g. `sip.telnyx.com`). Required for `kind=byoc`. */
    sipAddress?: string;
    /** SIP digest auth username. */
    authUsername?: string;
    /** Whether a SIP digest auth password is configured. The value is never returned. */
    authPasswordSet?: boolean;
    /** IP address / CIDR allowlist for inbound SIP connections. */
    allowedAddresses: string[];
    /**
     * ISO 3166-1 alpha-2 country code for the outbound dial plan
     * (e.g. `US`, `DE`). Required for international outbound on
     * some carriers.
     */
    destinationCountry?: string;
    transport: Speechify.SipTransport;
    mediaEncryption: Speechify.SipMediaEncryption;
    createdAt: Date;
    updatedAt: Date;
}
