/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * One child run inside a suite run, carrying the parent test's
 * name and the target agent's name so the grouped result view can
 * label each row. The agent name disambiguates results when the
 * suite spans multiple agents.
 */
export interface SuiteChildRun extends Speechify.AgentTestRun {
    /** Name of the test this run executed. */
    testName: string;
    /** Display name of the agent this run executed against. */
    agentName: string;
}
