/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Union-like result of a completed test run. Exactly one of
 * `reply`, `tool_call`, or `simulation` is populated, matching
 * the `test_type`.
 */
export interface TestRunResult {
    testType: Speechify.TestType;
    passed: boolean;
    /** Top-level verdict explanation duplicated from the inner result for quick rendering. */
    rationale: string;
    durationMs: number;
    reply?: Speechify.ReplyResult | null;
    toolCall?: Speechify.ToolCallResult | null;
    simulation?: Speechify.SimulationResult | null;
}
