/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * One of `SystemToolConfig`, `WebhookToolConfig`, `ClientToolConfig`, or `MCPToolConfig` depending on `kind`.
 */
export type ToolConfig =
    | Speechify.SystemToolConfig
    | Speechify.WebhookToolConfig
    | Speechify.ClientToolConfig
    | Speechify.McpToolConfig;
