/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Configuration for a `tool` test. The runner sends `context` as a
 * user message and asserts that the agent calls `expected_tool` with
 * arguments matching all `parameter_checks`. Use
 * `initial_chat_history` to test tool invocations that only make
 * sense mid-conversation.
 */
export interface ToolCallConfig {
    /** User message that should cause the agent to invoke the expected tool. Optional when `initial_chat_history` already ends with a user message. */
    context?: string;
    /**
     * Name of the tool the agent is expected to call. Leave empty to
     * invert the assertion: the test passes only when the agent calls
     * no tool at all.
     */
    expectedTool: string;
    /** Assertions on specific arguments of the tool call. */
    parameterChecks?: Speechify.ParameterCheck[];
    /** Optional seed conversation prepended before `context`. */
    initialChatHistory?: Speechify.SimulationMessage[];
    /**
     * Deprecated. Prefer the run-level `config_override`
     * on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
     * run-level override wins when both are set. Replaces the
     * agent's system prompt for this run only.
     */
    systemPromptOverride?: string;
    /**
     * Deprecated. Prefer the run-level `config_override`
     * on `POST /v1/agents/{id}/tests/runs`. Still honoured; the
     * run-level override wins when both are set. Overrides the LLM
     * model used by the agent for this run only.
     */
    modelOverride?: string;
}
