/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Body for POST /v1/workspaces/current/transfer-owner. The target
 * must already be a member of the current workspace — promote via
 * invite + accept first for external users.
 */
export interface TransferOwnershipRequest {
    /** Firebase UID of the member who will become the new owner. */
    userUid: string;
}
