/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Twilio credentials for the one-click import flow. Used only when
 * `source=twilio`. The Account SID and Auth Token are used to
 * provision an Elastic SIP Trunk on the customer's Twilio account
 * pointing at LiveKit's SIP endpoint, then stored for future trunk
 * management operations.
 */
export interface TwilioImportSpec {
    /** Twilio Account SID (starts with `AC`). */
    accountSid: string;
    /** Twilio Auth Token. Write-only - never echoed back. */
    authToken: string;
}
