/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Body for PUT /v1/workspaces/current/billing-contact-email.
 */
export interface UpdateBillingContactEmailRequest {
    /**
     * New billing contact email. Validated as an RFC 5322 address
     * (display-name forms are rejected); must be 254 characters
     * or fewer. Domain portion is lowercased for storage.
     */
    email: string;
}
