/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Post-call webhook delivery log row. One row per
 * `(conversation, webhook-url)`; updated in place across retry
 * attempts.
 */
export interface WebhookDelivery {
    id: string;
    /**
     * Prefixed wire identifier (`conv_<26 char Crockford base32>`)
     * of the conversation that triggered this delivery.
     */
    conversationId: string;
    /**
     * Prefixed wire identifier (`agent_<26 char Crockford base32>`)
     * of the agent.
     */
    agentId: string;
    url: string;
    event: string;
    status: Speechify.WebhookDeliveryStatus;
    attemptCount: number;
    lastAttemptAt?: Date;
    lastStatusCode?: number;
    lastError?: string;
    createdAt: Date;
}
