/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Result of a webhook probe. `ok` is true only when the endpoint
 * returned a 2xx. A non-2xx response still populates `status_code`
 * and `response_body` with `ok=false` — the request reached the
 * endpoint, the endpoint just declined it. `error` is set only for
 * transport-level failures (DNS, connect, TLS, timeout, blocked
 * address range) where no response was received; `status_code` is
 * absent in that case. `signed` reports whether the probe carried
 * an `X-Speechify-Signature` header — false on the create-form
 * flow, which has no stored secret yet. Both success and failure
 * use the 200 envelope so the console renders them inline.
 */
export interface WebhookProbeResult {
    ok: boolean;
    /** HTTP status the endpoint returned. Absent on a transport failure. */
    statusCode?: number;
    /** Wall-clock round-trip time in milliseconds. */
    latencyMs?: number;
    /** Truncated prefix (max ~2 KiB) of the endpoint's response body. */
    responseBody?: string;
    /** Whether the probe request carried an HMAC signature header. */
    signed: boolean;
    /** Human-readable transport-level failure reason. Absent when any response was received. */
    error?: string;
}
