/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Lifecycle of a post-call webhook delivery row. The sender
 * updates the same row across retries so the UI always sees the
 * latest outcome.
 */
export type WebhookDeliveryStatus = "pending" | "delivered" | "failed";
export const WebhookDeliveryStatus = {
    Pending: "pending",
    Delivered: "delivered",
    Failed: "failed",
} as const;
