/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WidgetConfigTranscript {
    enabled?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}
