/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WidgetConfigStyle = "pill" | "fab";
export const WidgetConfigStyle = {
    Pill: "pill",
    Fab: "fab",
} as const;
