/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../index";

/**
 * Customer-editable appearance + behaviour payload for the
 * embedded `<speechify-agent>` pill: button text, avatar style,
 * orb colours, terms-and-conditions markdown, transcript display.
 * Every field is optional - empty fields fall back to the
 * widget's compile-time defaults.
 */
export interface WidgetConfig {
    version?: number;
    style?: Speechify.WidgetConfigStyle;
    theme?: Speechify.WidgetConfigTheme;
    avatar?: Speechify.WidgetConfigAvatar;
    text?: Speechify.WidgetConfigText;
    terms?: Speechify.WidgetConfigTerms;
    transcript?: Speechify.WidgetConfigTranscript;
    /** Accepts any additional properties */
    [key: string]: any;
}
