/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WidgetConfigTheme = "dark" | "light" | "auto";
export const WidgetConfigTheme = {
    Dark: "dark",
    Light: "light",
    Auto: "auto",
} as const;
