/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { SipTrunkKind } from "../../../../../../types/SipTrunkKind";
import { SipTrunkDirection } from "../../../../../../types/SipTrunkDirection";
import { SipTransport } from "../../../../../../types/SipTransport";
import { SipMediaEncryption } from "../../../../../../types/SipMediaEncryption";

export const CreateSipTrunkRequest: core.serialization.Schema<
    serializers.agent.CreateSipTrunkRequest.Raw,
    Speechify.agent.CreateSipTrunkRequest
> = core.serialization.object({
    name: core.serialization.string(),
    kind: SipTrunkKind,
    direction: SipTrunkDirection,
    sipAddress: core.serialization.property("sip_address", core.serialization.string().optional()),
    authUsername: core.serialization.property("auth_username", core.serialization.string().optional()),
    authPassword: core.serialization.property("auth_password", core.serialization.string().optional()),
    allowedAddresses: core.serialization.property(
        "allowed_addresses",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    destinationCountry: core.serialization.property("destination_country", core.serialization.string().optional()),
    transport: SipTransport.optional(),
    mediaEncryption: core.serialization.property("media_encryption", SipMediaEncryption.optional()),
    credentials: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace CreateSipTrunkRequest {
    export interface Raw {
        name: string;
        kind: SipTrunkKind.Raw;
        direction: SipTrunkDirection.Raw;
        sip_address?: string | null;
        auth_username?: string | null;
        auth_password?: string | null;
        allowed_addresses?: string[] | null;
        destination_country?: string | null;
        transport?: SipTransport.Raw | null;
        media_encryption?: SipMediaEncryption.Raw | null;
        credentials?: Record<string, unknown> | null;
    }
}
