/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         config: {
 *             endpoint: "endpoint",
 *             auth: {
 *                 type: "none"
 *             }
 *         }
 *     }
 */
export interface TestMcpConnectionRequest {
    config: Speechify.McpToolConfig;
    /**
     * Optional `tool_<crockford>` id of the existing tool to hydrate
     * stored secrets from. Raw UUIDs and other-resource prefixes are
     * rejected.
     */
    toolId?: string;
}
