/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { PhoneNumberSource } from "../../../../../../types/PhoneNumberSource";
import { TwilioImportSpec } from "../../../../../../types/TwilioImportSpec";

export const ImportPhoneNumberRequest: core.serialization.Schema<
    serializers.agent.ImportPhoneNumberRequest.Raw,
    Speechify.agent.ImportPhoneNumberRequest
> = core.serialization.object({
    e164: core.serialization.string(),
    source: PhoneNumberSource,
    label: core.serialization.string().optional(),
    trunkId: core.serialization.property("trunk_id", core.serialization.string().optional()),
    agentId: core.serialization.property("agent_id", core.serialization.string().optional()),
    twilio: TwilioImportSpec.optional(),
});

export declare namespace ImportPhoneNumberRequest {
    export interface Raw {
        e164: string;
        source: PhoneNumberSource.Raw;
        label?: string | null;
        trunk_id?: string | null;
        agent_id?: string | null;
        twilio?: TwilioImportSpec.Raw | null;
    }
}
