/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const PurchasePhoneNumberRequest: core.serialization.Schema<
    serializers.agent.PurchasePhoneNumberRequest.Raw,
    Speechify.agent.PurchasePhoneNumberRequest
> = core.serialization.object({
    e164: core.serialization.string(),
    label: core.serialization.string().optional(),
    agentId: core.serialization.property("agent_id", core.serialization.string().optional()),
});

export declare namespace PurchasePhoneNumberRequest {
    export interface Raw {
        e164: string;
        label?: string | null;
        agent_id?: string | null;
    }
}
