// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         voice_id: "voice_id"
 *     }
 */
export interface GetVoicesRequest {
    /** The ID of the voice to fetch */
    voice_id: string;
}
