// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListVoicesRequest {
    /** Opaque pagination cursor from a previous response. */
    cursor?: string;
    /** Max items per page (default 50, max 200). */
    limit?: number;
}
