// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DownloadSampleVoicesRequest {
    /** The ID of the voice to download sample for */
    id: string;
}
