/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateInviteRequest: core.serialization.Schema<
    serializers.tts.CreateInviteRequest.Raw,
    Speechify.tts.CreateInviteRequest
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace CreateInviteRequest {
    export interface Raw {
        email: string;
    }
}
