/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const TransferOwnershipRequest: core.serialization.Schema<
    serializers.tts.TransferOwnershipRequest.Raw,
    Speechify.tts.TransferOwnershipRequest
> = core.serialization.object({
    userUid: core.serialization.property("user_uid", core.serialization.string()),
});

export declare namespace TransferOwnershipRequest {
    export interface Raw {
        user_uid: string;
    }
}
