/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         name: "Greet the caller by name",
 *         description: "Agent should greet the caller using their name when provided.",
 *         type: "scenario",
 *         config: {
 *             context: "The caller says: Hi, I'm Alice.",
 *             successCriteria: "The agent greets Alice by name.",
 *             successExamples: ["Hi Alice! How can I help you today?"],
 *             failureExamples: ["Hello! How can I help you?"]
 *         }
 *     }
 */
export interface CreateAgentTestRequest {
    /** Short human-readable label for the test. */
    name: string;
    /** Optional longer description of what this test verifies. */
    description?: string;
    type: Speechify.tts.TestType;
    /** Type-specific configuration. Must match the shape for the given `type`. */
    config: Speechify.tts.CreateAgentTestRequestConfig;
    /** Optional tool-mocking config applied during every run of this test. */
    toolMockConfig?: Speechify.tts.ToolMockConfig;
    /**
     * Per-test variable values substituted into string fields of the
     * config at run-start. Keys use the same rules as agent-level
     * `DynamicVariable` keys.
     */
    variables?: Record<string, unknown>;
    /** Folder to place the test in. Omit for root. */
    folderId?: string | null;
    /**
     * Optional list of additional agents this test should also run
     * against. The owner agent (path param) is always attached
     * implicitly.
     */
    attachedAgentIds?: string[];
}
