/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CreateSessionRequest {
    /** Opaque identifier for the end-user (e.g. your app's user ID). Stamped onto the conversation. Optional - defaults to an anonymous per-session ID. */
    userIdentity?: string;
    /**
     * Per-session variable overrides that merge on top of the agent's
     * stored variable defaults for this one session. Keys in the
     * reserved `system__` namespace are rejected at this boundary.
     * Values must match the declared type of the corresponding variable
     * definition on the agent (a `string` type expects a JSON string,
     * `number` expects a JSON number, etc.).
     */
    dynamicVariables?: Record<string, unknown>;
}
