/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CreateConversationRequest {
    /** Transport hint. Omit to use the agent's default. */
    transport?: string | null;
    /**
     * Per-session variable overrides that merge on top of the agent's
     * stored variable defaults for this one conversation. Keys in the
     * reserved `system__` namespace are rejected. Values must match the
     * declared type of the corresponding variable definition on the agent.
     */
    dynamicVariables?: Record<string, unknown>;
}
