/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AgentVoiceType } from "./AgentVoiceType";
import { AgentVoiceModel } from "./AgentVoiceModel";
import { AgentVoiceGender } from "./AgentVoiceGender";

export const AgentVoice: core.serialization.ObjectSchema<serializers.AgentVoice.Raw, Speechify.AgentVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        type: AgentVoiceType,
        displayName: core.serialization.property("display_name", core.serialization.string()),
        models: core.serialization.list(AgentVoiceModel),
        gender: AgentVoiceGender,
        locale: core.serialization.string(),
        previewAudio: core.serialization.property("preview_audio", core.serialization.string().nullable()),
        avatarImage: core.serialization.property("avatar_image", core.serialization.string().nullable()),
        tags: core.serialization.list(core.serialization.string()).optionalNullable(),
    });

export declare namespace AgentVoice {
    export interface Raw {
        id: string;
        type: AgentVoiceType.Raw;
        display_name: string;
        models: AgentVoiceModel.Raw[];
        gender: AgentVoiceGender.Raw;
        locale: string;
        preview_audio: string | null;
        avatar_image: string | null;
        tags?: (string[] | null) | null;
    }
}
