/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const AgentVoiceGender: core.serialization.Schema<serializers.AgentVoiceGender.Raw, Speechify.AgentVoiceGender> =
    core.serialization.enum_(["male", "female", "notSpecified"]);

export declare namespace AgentVoiceGender {
    export type Raw = "male" | "female" | "notSpecified";
}
