/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SuiteRunTrigger } from "./SuiteRunTrigger";
import { TestRunStatus } from "./TestRunStatus";
import { TestRunConfigOverride } from "./TestRunConfigOverride";

export const AgentTestSuiteRun: core.serialization.ObjectSchema<
    serializers.AgentTestSuiteRun.Raw,
    Speechify.AgentTestSuiteRun
> = core.serialization.object({
    id: core.serialization.string(),
    agentId: core.serialization.property("agent_id", core.serialization.string().optionalNullable()),
    agentName: core.serialization.property("agent_name", core.serialization.string().optionalNullable()),
    trigger: SuiteRunTrigger,
    parentSuiteRunId: core.serialization.property(
        "parent_suite_run_id",
        core.serialization.string().optionalNullable(),
    ),
    status: TestRunStatus,
    totalRuns: core.serialization.property("total_runs", core.serialization.number()),
    passedCount: core.serialization.property("passed_count", core.serialization.number()),
    failedCount: core.serialization.property("failed_count", core.serialization.number()),
    erroredCount: core.serialization.property("errored_count", core.serialization.number()),
    pendingCount: core.serialization.property("pending_count", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    completedAt: core.serialization.property("completed_at", core.serialization.date().optionalNullable()),
    configOverride: core.serialization.property("config_override", TestRunConfigOverride.optionalNullable()),
    flowVersionId: core.serialization.property("flow_version_id", core.serialization.string().optionalNullable()),
    flowVersionNumber: core.serialization.property(
        "flow_version_number",
        core.serialization.number().optionalNullable(),
    ),
});

export declare namespace AgentTestSuiteRun {
    export interface Raw {
        id: string;
        agent_id?: (string | null) | null;
        agent_name?: (string | null) | null;
        trigger: SuiteRunTrigger.Raw;
        parent_suite_run_id?: (string | null) | null;
        status: TestRunStatus.Raw;
        total_runs: number;
        passed_count: number;
        failed_count: number;
        errored_count: number;
        pending_count: number;
        created_at: string;
        completed_at?: (string | null) | null;
        config_override?: (TestRunConfigOverride.Raw | null) | null;
        flow_version_id?: (string | null) | null;
        flow_version_number?: (number | null) | null;
    }
}
