/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const AmdConfigOnVoicemailAction: core.serialization.Schema<
    serializers.AmdConfigOnVoicemailAction.Raw,
    Speechify.AmdConfigOnVoicemailAction
> = core.serialization.enum_(["hangup", "leave_message"]);

export declare namespace AmdConfigOnVoicemailAction {
    export type Raw = "hangup" | "leave_message";
}
