/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const AmdConfigTuning: core.serialization.ObjectSchema<
    serializers.AmdConfigTuning.Raw,
    Speechify.AmdConfigTuning
> = core.serialization.object({
    humanSpeechThresholdSeconds: core.serialization.property(
        "human_speech_threshold_seconds",
        core.serialization.number().optional(),
    ),
    noSpeechThresholdSeconds: core.serialization.property(
        "no_speech_threshold_seconds",
        core.serialization.number().optional(),
    ),
    timeoutSeconds: core.serialization.property("timeout_seconds", core.serialization.number().optional()),
    classificationPrompt: core.serialization.property("classification_prompt", core.serialization.string().optional()),
});

export declare namespace AmdConfigTuning {
    export interface Raw {
        human_speech_threshold_seconds?: number | null;
        no_speech_threshold_seconds?: number | null;
        timeout_seconds?: number | null;
        classification_prompt?: string | null;
    }
}
