/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AmdConfigOnVoicemail } from "./AmdConfigOnVoicemail";
import { AmdConfigOnIvr } from "./AmdConfigOnIvr";
import { AmdConfigOnUnavailable } from "./AmdConfigOnUnavailable";
import { AmdConfigTuning } from "./AmdConfigTuning";

export const AmdConfig: core.serialization.ObjectSchema<serializers.AmdConfig.Raw, Speechify.AmdConfig> =
    core.serialization.object({
        enabled: core.serialization.boolean(),
        onVoicemail: core.serialization.property("on_voicemail", AmdConfigOnVoicemail),
        onIvr: core.serialization.property("on_ivr", AmdConfigOnIvr),
        onUnavailable: core.serialization.property("on_unavailable", AmdConfigOnUnavailable),
        tuning: AmdConfigTuning.optional(),
    });

export declare namespace AmdConfig {
    export interface Raw {
        enabled: boolean;
        on_voicemail: AmdConfigOnVoicemail.Raw;
        on_ivr: AmdConfigOnIvr.Raw;
        on_unavailable: AmdConfigOnUnavailable.Raw;
        tuning?: AmdConfigTuning.Raw | null;
    }
}
