/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { Tool } from "./Tool";

export const AttachedToolsResponse: core.serialization.ObjectSchema<
    serializers.AttachedToolsResponse.Raw,
    Speechify.AttachedToolsResponse
> = core.serialization.object({
    tools: core.serialization.list(Tool),
});

export declare namespace AttachedToolsResponse {
    export interface Raw {
        tools: Tool.Raw[];
    }
}
