/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const AudioAsset: core.serialization.ObjectSchema<serializers.AudioAsset.Raw, Speechify.AudioAsset> =
    core.serialization.object({
        id: core.serialization.string(),
        originalFilename: core.serialization.property("original_filename", core.serialization.string()),
        contentType: core.serialization.property("content_type", core.serialization.string()),
        sizeBytes: core.serialization.property("size_bytes", core.serialization.number()),
        durationMs: core.serialization.property("duration_ms", core.serialization.number()),
        sampleRateHz: core.serialization.property("sample_rate_hz", core.serialization.number()),
        channels: core.serialization.number(),
        bitDepth: core.serialization.property("bit_depth", core.serialization.number()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace AudioAsset {
    export interface Raw {
        id: string;
        original_filename: string;
        content_type: string;
        size_bytes: number;
        duration_ms: number;
        sample_rate_hz: number;
        channels: number;
        bit_depth: number;
        created_at: string;
    }
}
