/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const BasicAuthConfig: core.serialization.ObjectSchema<
    serializers.BasicAuthConfig.Raw,
    Speechify.BasicAuthConfig
> = core.serialization.object({
    username: core.serialization.string(),
    password: core.serialization.string(),
});

export declare namespace BasicAuthConfig {
    export interface Raw {
        username: string;
        password: string;
    }
}
