/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const BatchCallStatus: core.serialization.Schema<serializers.BatchCallStatus.Raw, Speechify.BatchCallStatus> =
    core.serialization.enum_(["pending", "scheduled", "running", "completed", "failed", "cancelled"]);

export declare namespace BatchCallStatus {
    export type Raw = "pending" | "scheduled" | "running" | "completed" | "failed" | "cancelled";
}
