/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const BatchRecipientStatus: core.serialization.Schema<
    serializers.BatchRecipientStatus.Raw,
    Speechify.BatchRecipientStatus
> = core.serialization.enum_(["pending", "dialing", "completed", "failed"]);

export declare namespace BatchRecipientStatus {
    export type Raw = "pending" | "dialing" | "completed" | "failed";
}
