/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const BillingEntitlements: core.serialization.ObjectSchema<
    serializers.BillingEntitlements.Raw,
    Speechify.BillingEntitlements
> = core.serialization.object({
    phoneNumberQuota: core.serialization.property("phone_number_quota", core.serialization.number()),
    concurrentCallCap: core.serialization.property("concurrent_call_cap", core.serialization.number()),
    maxMembers: core.serialization.property("max_members", core.serialization.number()),
    maxCallDurationSeconds: core.serialization.property("max_call_duration_seconds", core.serialization.number()),
    canCreateWorkspaces: core.serialization.property("can_create_workspaces", core.serialization.boolean()),
    topupAllowed: core.serialization.property("topup_allowed", core.serialization.boolean()),
    voiceCloning: core.serialization.property("voice_cloning", core.serialization.boolean()),
    batchCalls: core.serialization.property("batch_calls", core.serialization.boolean()),
});

export declare namespace BillingEntitlements {
    export interface Raw {
        phone_number_quota: number;
        concurrent_call_cap: number;
        max_members: number;
        max_call_duration_seconds: number;
        can_create_workspaces: boolean;
        topup_allowed: boolean;
        voice_cloning: boolean;
        batch_calls: boolean;
    }
}
