/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { ToolParam } from "./ToolParam";

export const ClientToolConfig: core.serialization.ObjectSchema<
    serializers.ClientToolConfig.Raw,
    Speechify.ClientToolConfig
> = core.serialization.object({
    params: core.serialization.list(ToolParam).optional(),
    timeoutMs: core.serialization.property("timeout_ms", core.serialization.number().optional()),
});

export declare namespace ClientToolConfig {
    export interface Raw {
        params?: ToolParam.Raw[] | null;
        timeout_ms?: number | null;
    }
}
