/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const CreateWorkspaceRequest: core.serialization.ObjectSchema<
    serializers.CreateWorkspaceRequest.Raw,
    Speechify.CreateWorkspaceRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
});

export declare namespace CreateWorkspaceRequest {
    export interface Raw {
        name?: string | null;
    }
}
