/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { FlowGraphInput } from "./FlowGraphInput";

export const CreateFlowTemplateRequest: core.serialization.ObjectSchema<
    serializers.CreateFlowTemplateRequest.Raw,
    Speechify.CreateFlowTemplateRequest
> = core.serialization.object({
    key: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    category: core.serialization.string().optional(),
    graph: FlowGraphInput,
});

export declare namespace CreateFlowTemplateRequest {
    export interface Raw {
        key: string;
        name: string;
        description?: string | null;
        category?: string | null;
        graph: FlowGraphInput.Raw;
    }
}
