/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const CreateVoiceLanguage: core.serialization.ObjectSchema<
    serializers.CreateVoiceLanguage.Raw,
    Speechify.CreateVoiceLanguage
> = core.serialization.object({
    locale: core.serialization.string().optional(),
    previewAudio: core.serialization.property("preview_audio", core.serialization.string().optionalNullable()),
});

export declare namespace CreateVoiceLanguage {
    export interface Raw {
        locale?: string | null;
        preview_audio?: (string | null) | null;
    }
}
