/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { OAuth2ClientCredentialsConfig } from "./OAuth2ClientCredentialsConfig";
import { OAuth2JwtConfig } from "./OAuth2JwtConfig";
import { BasicAuthConfig } from "./BasicAuthConfig";
import { BearerAuthConfig } from "./BearerAuthConfig";
import { CustomHeadersConfig } from "./CustomHeadersConfig";

export const CredentialConfig: core.serialization.ObjectSchema<
    serializers.CredentialConfig.Raw,
    Speechify.CredentialConfig
> = core.serialization.object({
    oauth2ClientCredentials: core.serialization.property(
        "oauth2_client_credentials",
        OAuth2ClientCredentialsConfig.optional(),
    ),
    oauth2Jwt: core.serialization.property("oauth2_jwt", OAuth2JwtConfig.optional()),
    basic: BasicAuthConfig.optional(),
    bearer: BearerAuthConfig.optional(),
    customHeaders: core.serialization.property("custom_headers", CustomHeadersConfig.optional()),
});

export declare namespace CredentialConfig {
    export interface Raw {
        oauth2_client_credentials?: OAuth2ClientCredentialsConfig.Raw | null;
        oauth2_jwt?: OAuth2JwtConfig.Raw | null;
        basic?: BasicAuthConfig.Raw | null;
        bearer?: BearerAuthConfig.Raw | null;
        custom_headers?: CustomHeadersConfig.Raw | null;
    }
}
