/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { CredentialKind } from "./CredentialKind";
import { CredentialConfig } from "./CredentialConfig";

export const Credential: core.serialization.ObjectSchema<serializers.Credential.Raw, Speechify.Credential> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        kind: CredentialKind,
        config: CredentialConfig,
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace Credential {
    export interface Raw {
        id: string;
        name: string;
        kind: CredentialKind.Raw;
        config: CredentialConfig.Raw;
        created_at: string;
        updated_at: string;
    }
}
