/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const DataAssertionResultMode: core.serialization.Schema<
    serializers.DataAssertionResultMode.Raw,
    Speechify.DataAssertionResultMode
> = core.serialization.enum_(["exact", "regex", "llm"]);

export declare namespace DataAssertionResultMode {
    export type Raw = "exact" | "regex" | "llm";
}
