/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { ErrorCode } from "./ErrorCode";

export const ErrorDetail: core.serialization.ObjectSchema<serializers.ErrorDetail.Raw, Speechify.ErrorDetail> =
    core.serialization.object({
        code: ErrorCode,
        message: core.serialization.string(),
        fields: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    });

export declare namespace ErrorDetail {
    export interface Raw {
        code: ErrorCode.Raw;
        message: string;
        fields?: Record<string, string> | null;
    }
}
