/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const ErrorCode: core.serialization.Schema<serializers.ErrorCode.Raw, Speechify.ErrorCode> =
    core.serialization.enum_([
        "bad_request",
        "validation_failed",
        "unauthorized",
        "payment_required",
        "forbidden",
        "not_found",
        "method_not_allowed",
        "conflict",
        "payload_too_large",
        "unsupported_media_type",
        "rate_limited",
        "internal_error",
        "upstream_failure",
        "service_unavailable",
        "caller_not_found",
        "credential_not_found",
        "agent_not_found",
        "kb_not_found",
        "kb_document_not_found",
        "kb_folder_not_found",
        "tool_not_found",
        "conversation_not_found",
        "phone_number_not_found",
        "sip_trunk_not_found",
        "voice_not_found",
        "audio_asset_not_found",
        "builtin_not_found",
        "batch_not_found",
        "agent_test_not_found",
        "workspace_not_found",
        "invite_not_found",
        "insufficient_scope",
        "purchased_numbers_not_included",
        "phone_number_quota_reached",
        "batch_calls_not_included",
        "voice_cloning_not_included",
        "workspace_last_owner",
        "workspace_last_workspace",
        "invite_email_mismatch",
    ]);

export declare namespace ErrorCode {
    export type Raw =
        | "bad_request"
        | "validation_failed"
        | "unauthorized"
        | "payment_required"
        | "forbidden"
        | "not_found"
        | "method_not_allowed"
        | "conflict"
        | "payload_too_large"
        | "unsupported_media_type"
        | "rate_limited"
        | "internal_error"
        | "upstream_failure"
        | "service_unavailable"
        | "caller_not_found"
        | "credential_not_found"
        | "agent_not_found"
        | "kb_not_found"
        | "kb_document_not_found"
        | "kb_folder_not_found"
        | "tool_not_found"
        | "conversation_not_found"
        | "phone_number_not_found"
        | "sip_trunk_not_found"
        | "voice_not_found"
        | "audio_asset_not_found"
        | "builtin_not_found"
        | "batch_not_found"
        | "agent_test_not_found"
        | "workspace_not_found"
        | "invite_not_found"
        | "insufficient_scope"
        | "purchased_numbers_not_included"
        | "phone_number_quota_reached"
        | "batch_calls_not_included"
        | "voice_cloning_not_included"
        | "workspace_last_owner"
        | "workspace_last_workspace"
        | "invite_email_mismatch";
}
