/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const EvaluationStatus: core.serialization.Schema<serializers.EvaluationStatus.Raw, Speechify.EvaluationStatus> =
    core.serialization.enum_(["success", "failure", "unknown"]);

export declare namespace EvaluationStatus {
    export type Raw = "success" | "failure" | "unknown";
}
