/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { FlowGraph } from "./FlowGraph";

export const FlowTemplate: core.serialization.ObjectSchema<serializers.FlowTemplate.Raw, Speechify.FlowTemplate> =
    core.serialization.object({
        id: core.serialization.string(),
        key: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        category: core.serialization.string(),
        graph: FlowGraph,
        isSeed: core.serialization.property("is_seed", core.serialization.boolean()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace FlowTemplate {
    export interface Raw {
        id: string;
        key: string;
        name: string;
        description?: string | null;
        category: string;
        graph: FlowGraph.Raw;
        is_seed: boolean;
        created_at: string;
        updated_at: string;
    }
}
