/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { FlowGraph } from "./FlowGraph";
import { FlowVersion } from "./FlowVersion";

export const GetFlowResponse: core.serialization.ObjectSchema<
    serializers.GetFlowResponse.Raw,
    Speechify.GetFlowResponse
> = core.serialization.object({
    draft: FlowGraph.optional(),
    active: FlowGraph.optional(),
    history: core.serialization.list(FlowVersion),
});

export declare namespace GetFlowResponse {
    export interface Raw {
        draft?: FlowGraph.Raw | null;
        active?: FlowGraph.Raw | null;
        history: FlowVersion.Raw[];
    }
}
