/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { ImportJobKind } from "./ImportJobKind";
import { ImportJobStatus } from "./ImportJobStatus";

export const ImportJob: core.serialization.ObjectSchema<serializers.ImportJob.Raw, Speechify.ImportJob> =
    core.serialization.object({
        id: core.serialization.string(),
        kbId: core.serialization.property("kb_id", core.serialization.string()),
        kind: ImportJobKind,
        status: ImportJobStatus,
        requestedCount: core.serialization.property("requested_count", core.serialization.number()),
        completedCount: core.serialization.property("completed_count", core.serialization.number()),
        failedCount: core.serialization.property("failed_count", core.serialization.number()),
        params: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        error: core.serialization.string().optional(),
        upstreamJobId: core.serialization.property("upstream_job_id", core.serialization.string().optional()),
        createdByUid: core.serialization.property("created_by_uid", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        startedAt: core.serialization.property("started_at", core.serialization.date().nullable()),
        finishedAt: core.serialization.property("finished_at", core.serialization.date().nullable()),
    });

export declare namespace ImportJob {
    export interface Raw {
        id: string;
        kb_id: string;
        kind: ImportJobKind.Raw;
        status: ImportJobStatus.Raw;
        requested_count: number;
        completed_count: number;
        failed_count: number;
        params: Record<string, unknown>;
        error?: string | null;
        upstream_job_id?: string | null;
        created_by_uid: string;
        created_at: string;
        updated_at: string;
        started_at: string | null;
        finished_at: string | null;
    }
}
