/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { MemberRole } from "./MemberRole";

export const Invite: core.serialization.ObjectSchema<serializers.Invite.Raw, Speechify.Invite> =
    core.serialization.object({
        id: core.serialization.string(),
        email: core.serialization.string(),
        invitedBy: core.serialization.property("invited_by", core.serialization.string()),
        role: MemberRole,
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        expiresAt: core.serialization.property("expires_at", core.serialization.date()),
        acceptedAt: core.serialization.property("accepted_at", core.serialization.date().optional()),
        revokedAt: core.serialization.property("revoked_at", core.serialization.date().optional()),
        token: core.serialization.string().optional(),
        emailSent: core.serialization.property("email_sent", core.serialization.boolean()),
    });

export declare namespace Invite {
    export interface Raw {
        id: string;
        email: string;
        invited_by: string;
        role: MemberRole.Raw;
        created_at: string;
        expires_at: string;
        accepted_at?: string | null;
        revoked_at?: string | null;
        token?: string | null;
        email_sent: boolean;
    }
}
