/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const InvitePreview: core.serialization.ObjectSchema<serializers.InvitePreview.Raw, Speechify.InvitePreview> =
    core.serialization.object({
        tenantId: core.serialization.property("tenant_id", core.serialization.string()),
        tenantName: core.serialization.property("tenant_name", core.serialization.string()),
        invitedEmail: core.serialization.property("invited_email", core.serialization.string()),
        invitedByEmail: core.serialization.property("invited_by_email", core.serialization.string().optional()),
        invitedByDisplayName: core.serialization.property(
            "invited_by_display_name",
            core.serialization.string().optional(),
        ),
        expiresAt: core.serialization.property("expires_at", core.serialization.date()),
    });

export declare namespace InvitePreview {
    export interface Raw {
        tenant_id: string;
        tenant_name: string;
        invited_email: string;
        invited_by_email?: string | null;
        invited_by_display_name?: string | null;
        expires_at: string;
    }
}
