/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const IvrMenuListEntry: core.serialization.ObjectSchema<
    serializers.IvrMenuListEntry.Raw,
    Speechify.IvrMenuListEntry
> = core.serialization.object({
    menuId: core.serialization.property("menu_id", core.serialization.string()),
    fingerprintId: core.serialization.property("fingerprint_id", core.serialization.string()),
    fingerprintHash: core.serialization.property("fingerprint_hash", core.serialization.string()),
    transcriptSample: core.serialization.property("transcript_sample", core.serialization.string()),
    schemaVersion: core.serialization.property("schema_version", core.serialization.number()),
    menuTree: core.serialization.property(
        "menu_tree",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
    confidenceScore: core.serialization.property("confidence_score", core.serialization.number()),
    succeededTraversals: core.serialization.property("succeeded_traversals", core.serialization.number()),
    totalTraversals: core.serialization.property("total_traversals", core.serialization.number()),
    lastValidatedAt: core.serialization.property("last_validated_at", core.serialization.date()),
    lastObservedAt: core.serialization.property("last_observed_at", core.serialization.date()),
    occurrenceCount: core.serialization.property("occurrence_count", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace IvrMenuListEntry {
    export interface Raw {
        menu_id: string;
        fingerprint_id: string;
        fingerprint_hash: string;
        transcript_sample: string;
        schema_version: number;
        menu_tree: Record<string, unknown>;
        confidence_score: number;
        succeeded_traversals: number;
        total_traversals: number;
        last_validated_at: string;
        last_observed_at: string;
        occurrence_count: number;
        created_at: string;
    }
}
