/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const IvrMenu: core.serialization.ObjectSchema<serializers.IvrMenu.Raw, Speechify.IvrMenu> =
    core.serialization.object({
        id: core.serialization.string(),
        fingerprintId: core.serialization.property("fingerprint_id", core.serialization.string()),
        tenantId: core.serialization.property("tenant_id", core.serialization.string().optionalNullable()),
        schemaVersion: core.serialization.property("schema_version", core.serialization.number()),
        menuTree: core.serialization.property(
            "menu_tree",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        ),
        confidenceScore: core.serialization.property("confidence_score", core.serialization.number()),
        succeededTraversals: core.serialization.property("succeeded_traversals", core.serialization.number()),
        totalTraversals: core.serialization.property("total_traversals", core.serialization.number()),
        lastValidatedAt: core.serialization.property("last_validated_at", core.serialization.date()),
        invalidatedAt: core.serialization.property("invalidated_at", core.serialization.date().optionalNullable()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace IvrMenu {
    export interface Raw {
        id: string;
        fingerprint_id: string;
        tenant_id?: (string | null) | null;
        schema_version: number;
        menu_tree: Record<string, unknown>;
        confidence_score: number;
        succeeded_traversals: number;
        total_traversals: number;
        last_validated_at: string;
        invalidated_at?: (string | null) | null;
        created_at: string;
        updated_at: string;
    }
}
