/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const KnowledgeBase: core.serialization.ObjectSchema<serializers.KnowledgeBase.Raw, Speechify.KnowledgeBase> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
        documentCount: core.serialization.property("document_count", core.serialization.number()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace KnowledgeBase {
    export interface Raw {
        id: string;
        name: string;
        description: string;
        document_count: number;
        created_at: string;
        updated_at: string;
    }
}
