/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const KnowledgeBaseFolder: core.serialization.ObjectSchema<
    serializers.KnowledgeBaseFolder.Raw,
    Speechify.KnowledgeBaseFolder
> = core.serialization.object({
    id: core.serialization.string(),
    kbId: core.serialization.property("kb_id", core.serialization.string()),
    parentFolderId: core.serialization.property("parent_folder_id", core.serialization.string().nullable()),
    name: core.serialization.string(),
    documentCount: core.serialization.property("document_count", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace KnowledgeBaseFolder {
    export interface Raw {
        id: string;
        kb_id: string;
        parent_folder_id: string | null;
        name: string;
        document_count: number;
        created_at: string;
        updated_at: string;
    }
}
