/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { FlowVersion } from "./FlowVersion";

export const ListFlowVersionsResponse: core.serialization.ObjectSchema<
    serializers.ListFlowVersionsResponse.Raw,
    Speechify.ListFlowVersionsResponse
> = core.serialization.object({
    versions: core.serialization.list(FlowVersion),
});

export declare namespace ListFlowVersionsResponse {
    export interface Raw {
        versions: FlowVersion.Raw[];
    }
}
