/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { IvrMenuListEntry } from "./IvrMenuListEntry";

export const ListIvrMenusResponse: core.serialization.ObjectSchema<
    serializers.ListIvrMenusResponse.Raw,
    Speechify.ListIvrMenusResponse
> = core.serialization.object({
    menus: core.serialization.list(IvrMenuListEntry),
});

export declare namespace ListIvrMenusResponse {
    export interface Raw {
        menus: IvrMenuListEntry.Raw[];
    }
}
