/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { BatchCall } from "./BatchCall";
import { PaginationMeta } from "./PaginationMeta";

export const ListBatchCallsResponse: core.serialization.ObjectSchema<
    serializers.ListBatchCallsResponse.Raw,
    Speechify.ListBatchCallsResponse
> = core.serialization
    .object({
        batches: core.serialization.list(BatchCall),
    })
    .extend(PaginationMeta);

export declare namespace ListBatchCallsResponse {
    export interface Raw extends PaginationMeta.Raw {
        batches: BatchCall.Raw[];
    }
}
