/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { KnowledgeBaseChunk } from "./KnowledgeBaseChunk";
import { PaginationMeta } from "./PaginationMeta";

export const ListKnowledgeBaseChunksResponse: core.serialization.ObjectSchema<
    serializers.ListKnowledgeBaseChunksResponse.Raw,
    Speechify.ListKnowledgeBaseChunksResponse
> = core.serialization
    .object({
        chunks: core.serialization.list(KnowledgeBaseChunk),
    })
    .extend(PaginationMeta);

export declare namespace ListKnowledgeBaseChunksResponse {
    export interface Raw extends PaginationMeta.Raw {
        chunks: KnowledgeBaseChunk.Raw[];
    }
}
