/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AgentTestFolder } from "./AgentTestFolder";

export const ListAgentTestFoldersResponse: core.serialization.ObjectSchema<
    serializers.ListAgentTestFoldersResponse.Raw,
    Speechify.ListAgentTestFoldersResponse
> = core.serialization.object({
    folders: core.serialization.list(AgentTestFolder),
});

export declare namespace ListAgentTestFoldersResponse {
    export interface Raw {
        folders: AgentTestFolder.Raw[];
    }
}
