/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SipTrunk } from "./SipTrunk";

export const ListSipTrunksResponse: core.serialization.ObjectSchema<
    serializers.ListSipTrunksResponse.Raw,
    Speechify.ListSipTrunksResponse
> = core.serialization.object({
    trunks: core.serialization.list(SipTrunk),
});

export declare namespace ListSipTrunksResponse {
    export interface Raw {
        trunks: SipTrunk.Raw[];
    }
}
