/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { Conversation } from "./Conversation";
import { PaginationMeta } from "./PaginationMeta";

export const ListCallerConversationsResponse: core.serialization.ObjectSchema<
    serializers.ListCallerConversationsResponse.Raw,
    Speechify.ListCallerConversationsResponse
> = core.serialization
    .object({
        conversations: core.serialization.list(Conversation),
    })
    .extend(PaginationMeta);

export declare namespace ListCallerConversationsResponse {
    export interface Raw extends PaginationMeta.Raw {
        conversations: Conversation.Raw[];
    }
}
