/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AgentTestWithLastRun } from "./AgentTestWithLastRun";

export const ListAgentTestsResponse: core.serialization.ObjectSchema<
    serializers.ListAgentTestsResponse.Raw,
    Speechify.ListAgentTestsResponse
> = core.serialization.object({
    tests: core.serialization.list(AgentTestWithLastRun),
});

export declare namespace ListAgentTestsResponse {
    export interface Raw {
        tests: AgentTestWithLastRun.Raw[];
    }
}
