/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { RecentCallee } from "./RecentCallee";
import { PaginationMeta } from "./PaginationMeta";

export const ListRecentCalleesResponse: core.serialization.ObjectSchema<
    serializers.ListRecentCalleesResponse.Raw,
    Speechify.ListRecentCalleesResponse
> = core.serialization
    .object({
        callees: core.serialization.list(RecentCallee),
    })
    .extend(PaginationMeta);

export declare namespace ListRecentCalleesResponse {
    export interface Raw extends PaginationMeta.Raw {
        callees: RecentCallee.Raw[];
    }
}
