/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { KnowledgeBase } from "./KnowledgeBase";
import { PaginationMeta } from "./PaginationMeta";

export const ListKnowledgeBasesResponse: core.serialization.ObjectSchema<
    serializers.ListKnowledgeBasesResponse.Raw,
    Speechify.ListKnowledgeBasesResponse
> = core.serialization
    .object({
        knowledgeBases: core.serialization.property("knowledge_bases", core.serialization.list(KnowledgeBase)),
    })
    .extend(PaginationMeta);

export declare namespace ListKnowledgeBasesResponse {
    export interface Raw extends PaginationMeta.Raw {
        knowledge_bases: KnowledgeBase.Raw[];
    }
}
