/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AgentTestRun } from "./AgentTestRun";
import { PaginationMeta } from "./PaginationMeta";

export const ListAgentTestRunsResponse: core.serialization.ObjectSchema<
    serializers.ListAgentTestRunsResponse.Raw,
    Speechify.ListAgentTestRunsResponse
> = core.serialization
    .object({
        runs: core.serialization.list(AgentTestRun),
    })
    .extend(PaginationMeta);

export declare namespace ListAgentTestRunsResponse {
    export interface Raw extends PaginationMeta.Raw {
        runs: AgentTestRun.Raw[];
    }
}
