/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { ToolAttachedAgent } from "./ToolAttachedAgent";

export const ListToolAttachedAgentsResponse: core.serialization.ObjectSchema<
    serializers.ListToolAttachedAgentsResponse.Raw,
    Speechify.ListToolAttachedAgentsResponse
> = core.serialization.object({
    agents: core.serialization.list(ToolAttachedAgent),
});

export declare namespace ListToolAttachedAgentsResponse {
    export interface Raw {
        agents: ToolAttachedAgent.Raw[];
    }
}
