/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { Tool } from "./Tool";
import { PaginationMeta } from "./PaginationMeta";

export const ListToolsResponse: core.serialization.ObjectSchema<
    serializers.ListToolsResponse.Raw,
    Speechify.ListToolsResponse
> = core.serialization
    .object({
        tools: core.serialization.list(Tool),
    })
    .extend(PaginationMeta);

export declare namespace ListToolsResponse {
    export interface Raw extends PaginationMeta.Raw {
        tools: Tool.Raw[];
    }
}
