/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { McpProbeErrorDetailsStage } from "./McpProbeErrorDetailsStage";

export const McpProbeErrorDetails: core.serialization.ObjectSchema<
    serializers.McpProbeErrorDetails.Raw,
    Speechify.McpProbeErrorDetails
> = core.serialization.object({
    stage: McpProbeErrorDetailsStage.optional(),
    httpStatus: core.serialization.property("http_status", core.serialization.number().optional()),
    oauth2Error: core.serialization.property("oauth2_error", core.serialization.string().optional()),
    oauth2ErrorDescription: core.serialization.property(
        "oauth2_error_description",
        core.serialization.string().optional(),
    ),
    upstreamBody: core.serialization.property("upstream_body", core.serialization.string().optional()),
    fieldHint: core.serialization.property("field_hint", core.serialization.string().optional()),
});

export declare namespace McpProbeErrorDetails {
    export interface Raw {
        stage?: McpProbeErrorDetailsStage.Raw | null;
        http_status?: number | null;
        oauth2_error?: string | null;
        oauth2_error_description?: string | null;
        upstream_body?: string | null;
        field_hint?: string | null;
    }
}
