/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { McpProbeTool } from "./McpProbeTool";
import { McpProbeErrorDetails } from "./McpProbeErrorDetails";

export const McpProbeResult: core.serialization.ObjectSchema<serializers.McpProbeResult.Raw, Speechify.McpProbeResult> =
    core.serialization.object({
        tools: core.serialization.list(McpProbeTool).nullable(),
        error: core.serialization.string().optional(),
        details: McpProbeErrorDetails.optional(),
    });

export declare namespace McpProbeResult {
    export interface Raw {
        tools: McpProbeTool.Raw[] | null;
        error?: string | null;
        details?: McpProbeErrorDetails.Raw | null;
    }
}
