/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { McpTransport } from "./McpTransport";
import { McpAuth } from "./McpAuth";

export const McpToolConfig: core.serialization.ObjectSchema<serializers.McpToolConfig.Raw, Speechify.McpToolConfig> =
    core.serialization.object({
        endpoint: core.serialization.string(),
        transport: McpTransport.optional(),
        auth: McpAuth,
    });

export declare namespace McpToolConfig {
    export interface Raw {
        endpoint: string;
        transport?: McpTransport.Raw | null;
        auth: McpAuth.Raw;
    }
}
