/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { Member } from "./Member";

export const MembersListResponse: core.serialization.ObjectSchema<
    serializers.MembersListResponse.Raw,
    Speechify.MembersListResponse
> = core.serialization.object({
    members: core.serialization.list(Member),
});

export declare namespace MembersListResponse {
    export interface Raw {
        members: Member.Raw[];
    }
}
