/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { PhoneNumberSource } from "./PhoneNumberSource";
import { PhoneNumberCapability } from "./PhoneNumberCapability";

export const PhoneNumber: core.serialization.ObjectSchema<serializers.PhoneNumber.Raw, Speechify.PhoneNumber> =
    core.serialization.object({
        id: core.serialization.string(),
        e164: core.serialization.string(),
        source: PhoneNumberSource,
        label: core.serialization.string().optional(),
        trunkId: core.serialization.property("trunk_id", core.serialization.string().optional()),
        agentId: core.serialization.property("agent_id", core.serialization.string().optional()),
        capabilities: core.serialization.list(PhoneNumberCapability),
        livekitPhoneNumberId: core.serialization.property(
            "livekit_phone_number_id",
            core.serialization.string().optional(),
        ),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace PhoneNumber {
    export interface Raw {
        id: string;
        e164: string;
        source: PhoneNumberSource.Raw;
        label?: string | null;
        trunk_id?: string | null;
        agent_id?: string | null;
        capabilities: PhoneNumberCapability.Raw[];
        livekit_phone_number_id?: string | null;
        created_at: string;
        updated_at: string;
    }
}
