/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SimulationMessage } from "./SimulationMessage";

export const ReplyConfig: core.serialization.ObjectSchema<serializers.ReplyConfig.Raw, Speechify.ReplyConfig> =
    core.serialization.object({
        context: core.serialization.string().optional(),
        successCriteria: core.serialization.property("success_criteria", core.serialization.string()),
        successExamples: core.serialization.property(
            "success_examples",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        failureExamples: core.serialization.property(
            "failure_examples",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        initialChatHistory: core.serialization.property(
            "initial_chat_history",
            core.serialization.list(SimulationMessage).optional(),
        ),
        systemPromptOverride: core.serialization.property(
            "system_prompt_override",
            core.serialization.string().optional(),
        ),
        firstMessageOverride: core.serialization.property(
            "first_message_override",
            core.serialization.string().optional(),
        ),
        modelOverride: core.serialization.property("model_override", core.serialization.string().optional()),
    });

export declare namespace ReplyConfig {
    export interface Raw {
        context?: string | null;
        success_criteria: string;
        success_examples?: string[] | null;
        failure_examples?: string[] | null;
        initial_chat_history?: SimulationMessage.Raw[] | null;
        system_prompt_override?: string | null;
        first_message_override?: string | null;
        model_override?: string | null;
    }
}
