/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { RetrievalLogResult } from "./RetrievalLogResult";

export const RetrievalLogEntry: core.serialization.ObjectSchema<
    serializers.RetrievalLogEntry.Raw,
    Speechify.RetrievalLogEntry
> = core.serialization.object({
    id: core.serialization.string(),
    conversationId: core.serialization.property("conversation_id", core.serialization.string()),
    query: core.serialization.string(),
    results: core.serialization.list(RetrievalLogResult),
    topK: core.serialization.property("top_k", core.serialization.number()),
    hitCount: core.serialization.property("hit_count", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace RetrievalLogEntry {
    export interface Raw {
        id: string;
        conversation_id: string;
        query: string;
        results: RetrievalLogResult.Raw[];
        top_k: number;
        hit_count: number;
        created_at: string;
    }
}
