/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AvailablePhoneNumber } from "./AvailablePhoneNumber";

export const SearchAvailablePhoneNumbersResponse: core.serialization.ObjectSchema<
    serializers.SearchAvailablePhoneNumbersResponse.Raw,
    Speechify.SearchAvailablePhoneNumbersResponse
> = core.serialization.object({
    numbers: core.serialization.list(AvailablePhoneNumber),
});

export declare namespace SearchAvailablePhoneNumbersResponse {
    export interface Raw {
        numbers: AvailablePhoneNumber.Raw[];
    }
}
