/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SimulationMessageRole } from "./SimulationMessageRole";

export const SimulationMessage: core.serialization.ObjectSchema<
    serializers.SimulationMessage.Raw,
    Speechify.SimulationMessage
> = core.serialization.object({
    role: SimulationMessageRole,
    content: core.serialization.string(),
});

export declare namespace SimulationMessage {
    export interface Raw {
        role: SimulationMessageRole.Raw;
        content: string;
    }
}
