/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const SimulationResultSentiment: core.serialization.Schema<
    serializers.SimulationResultSentiment.Raw,
    Speechify.SimulationResultSentiment
> = core.serialization.enum_(["positive", "neutral", "negative"]);

export declare namespace SimulationResultSentiment {
    export type Raw = "positive" | "neutral" | "negative";
}
