/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const SipMediaEncryption: core.serialization.Schema<
    serializers.SipMediaEncryption.Raw,
    Speechify.SipMediaEncryption
> = core.serialization.enum_(["disable", "allow", "require"]);

export declare namespace SipMediaEncryption {
    export type Raw = "disable" | "allow" | "require";
}
