/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SipTrunkKind } from "./SipTrunkKind";
import { SipTrunkDirection } from "./SipTrunkDirection";
import { SipTransport } from "./SipTransport";
import { SipMediaEncryption } from "./SipMediaEncryption";

export const SipTrunk: core.serialization.ObjectSchema<serializers.SipTrunk.Raw, Speechify.SipTrunk> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        kind: SipTrunkKind,
        direction: SipTrunkDirection,
        livekitInboundTrunkId: core.serialization.property(
            "livekit_inbound_trunk_id",
            core.serialization.string().optional(),
        ),
        livekitOutboundTrunkId: core.serialization.property(
            "livekit_outbound_trunk_id",
            core.serialization.string().optional(),
        ),
        livekitDispatchRuleId: core.serialization.property(
            "livekit_dispatch_rule_id",
            core.serialization.string().optional(),
        ),
        sipAddress: core.serialization.property("sip_address", core.serialization.string().optional()),
        authUsername: core.serialization.property("auth_username", core.serialization.string().optional()),
        authPasswordSet: core.serialization.property("auth_password_set", core.serialization.boolean().optional()),
        allowedAddresses: core.serialization.property(
            "allowed_addresses",
            core.serialization.list(core.serialization.string()),
        ),
        destinationCountry: core.serialization.property("destination_country", core.serialization.string().optional()),
        transport: SipTransport,
        mediaEncryption: core.serialization.property("media_encryption", SipMediaEncryption),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    });

export declare namespace SipTrunk {
    export interface Raw {
        id: string;
        name: string;
        kind: SipTrunkKind.Raw;
        direction: SipTrunkDirection.Raw;
        livekit_inbound_trunk_id?: string | null;
        livekit_outbound_trunk_id?: string | null;
        livekit_dispatch_rule_id?: string | null;
        sip_address?: string | null;
        auth_username?: string | null;
        auth_password_set?: boolean | null;
        allowed_addresses: string[];
        destination_country?: string | null;
        transport: SipTransport.Raw;
        media_encryption: SipMediaEncryption.Raw;
        created_at: string;
        updated_at: string;
    }
}
