/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const SuiteRunTrigger: core.serialization.Schema<serializers.SuiteRunTrigger.Raw, Speechify.SuiteRunTrigger> =
    core.serialization.enum_(["run_all", "batch", "resubmit"]);

export declare namespace SuiteRunTrigger {
    export type Raw = "run_all" | "batch" | "resubmit";
}
