/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { MemberRole } from "./MemberRole";

export const Tenant: core.serialization.ObjectSchema<serializers.Tenant.Raw, Speechify.Tenant> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        orbCustomerId: core.serialization.property("orb_customer_id", core.serialization.string().optional()),
        billingContactEmail: core.serialization.property(
            "billing_contact_email",
            core.serialization.string().optional(),
        ),
        billingContactName: core.serialization.property(
            "billing_contact_name",
            core.serialization.string().optionalNullable(),
        ),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        myRole: core.serialization.property("my_role", MemberRole),
    });

export declare namespace Tenant {
    export interface Raw {
        id: string;
        name: string;
        orb_customer_id?: string | null;
        billing_contact_email?: string | null;
        billing_contact_name?: (string | null) | null;
        created_at: string;
        updated_at: string;
        my_role: MemberRole.Raw;
    }
}
