/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const TestStatsBucket: core.serialization.ObjectSchema<
    serializers.TestStatsBucket.Raw,
    Speechify.TestStatsBucket
> = core.serialization.object({
    day: core.serialization.string(),
    passed: core.serialization.number(),
    failed: core.serialization.number(),
    errored: core.serialization.number(),
});

export declare namespace TestStatsBucket {
    export interface Raw {
        day: string;
        passed: number;
        failed: number;
        errored: number;
    }
}
