/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { TestType } from "./TestType";
import { ReplyResult } from "./ReplyResult";
import { ToolCallResult } from "./ToolCallResult";
import { SimulationResult } from "./SimulationResult";

export const TestRunResult: core.serialization.ObjectSchema<serializers.TestRunResult.Raw, Speechify.TestRunResult> =
    core.serialization.object({
        testType: core.serialization.property("test_type", TestType),
        passed: core.serialization.boolean(),
        rationale: core.serialization.string(),
        durationMs: core.serialization.property("duration_ms", core.serialization.number()),
        reply: ReplyResult.optionalNullable(),
        toolCall: core.serialization.property("tool_call", ToolCallResult.optionalNullable()),
        simulation: SimulationResult.optionalNullable(),
    });

export declare namespace TestRunResult {
    export interface Raw {
        test_type: TestType.Raw;
        passed: boolean;
        rationale: string;
        duration_ms: number;
        reply?: (ReplyResult.Raw | null) | null;
        tool_call?: (ToolCallResult.Raw | null) | null;
        simulation?: (SimulationResult.Raw | null) | null;
    }
}
