/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { ParameterCheck } from "./ParameterCheck";
import { SimulationMessage } from "./SimulationMessage";

export const ToolCallConfig: core.serialization.ObjectSchema<serializers.ToolCallConfig.Raw, Speechify.ToolCallConfig> =
    core.serialization.object({
        context: core.serialization.string().optional(),
        expectedTool: core.serialization.property("expected_tool", core.serialization.string()),
        parameterChecks: core.serialization.property(
            "parameter_checks",
            core.serialization.list(ParameterCheck).optional(),
        ),
        initialChatHistory: core.serialization.property(
            "initial_chat_history",
            core.serialization.list(SimulationMessage).optional(),
        ),
        systemPromptOverride: core.serialization.property(
            "system_prompt_override",
            core.serialization.string().optional(),
        ),
        modelOverride: core.serialization.property("model_override", core.serialization.string().optional()),
    });

export declare namespace ToolCallConfig {
    export interface Raw {
        context?: string | null;
        expected_tool: string;
        parameter_checks?: ParameterCheck.Raw[] | null;
        initial_chat_history?: SimulationMessage.Raw[] | null;
        system_prompt_override?: string | null;
        model_override?: string | null;
    }
}
