/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const ToolKind: core.serialization.Schema<serializers.ToolKind.Raw, Speechify.ToolKind> =
    core.serialization.enum_(["system", "webhook", "client", "mcp"]);

export declare namespace ToolKind {
    export type Raw = "system" | "webhook" | "client" | "mcp";
}
