/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const UpdateBillingContactEmailRequest: core.serialization.ObjectSchema<
    serializers.UpdateBillingContactEmailRequest.Raw,
    Speechify.UpdateBillingContactEmailRequest
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace UpdateBillingContactEmailRequest {
    export interface Raw {
        email: string;
    }
}
