/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { SipTransport } from "./SipTransport";
import { SipMediaEncryption } from "./SipMediaEncryption";

export const UpdateSipTrunkRequest: core.serialization.ObjectSchema<
    serializers.UpdateSipTrunkRequest.Raw,
    Speechify.UpdateSipTrunkRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    authUsername: core.serialization.property("auth_username", core.serialization.string().optional()),
    authPassword: core.serialization.property("auth_password", core.serialization.string().optional()),
    allowedAddresses: core.serialization.property(
        "allowed_addresses",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    destinationCountry: core.serialization.property("destination_country", core.serialization.string().optional()),
    transport: SipTransport.optional(),
    mediaEncryption: core.serialization.property("media_encryption", SipMediaEncryption.optional()),
});

export declare namespace UpdateSipTrunkRequest {
    export interface Raw {
        name?: string | null;
        auth_username?: string | null;
        auth_password?: string | null;
        allowed_addresses?: string[] | null;
        destination_country?: string | null;
        transport?: SipTransport.Raw | null;
        media_encryption?: SipMediaEncryption.Raw | null;
    }
}
