/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { AudioAsset } from "./AudioAsset";

export const UploadAudioAssetResponse: core.serialization.ObjectSchema<
    serializers.UploadAudioAssetResponse.Raw,
    Speechify.UploadAudioAssetResponse
> = core.serialization.object({
    asset: AudioAsset,
});

export declare namespace UploadAudioAssetResponse {
    export interface Raw {
        asset: AudioAsset.Raw;
    }
}
