/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { WebhookDeliveryStatus } from "./WebhookDeliveryStatus";

export const WebhookDelivery: core.serialization.ObjectSchema<
    serializers.WebhookDelivery.Raw,
    Speechify.WebhookDelivery
> = core.serialization.object({
    id: core.serialization.string(),
    conversationId: core.serialization.property("conversation_id", core.serialization.string()),
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    url: core.serialization.string(),
    event: core.serialization.string(),
    status: WebhookDeliveryStatus,
    attemptCount: core.serialization.property("attempt_count", core.serialization.number()),
    lastAttemptAt: core.serialization.property("last_attempt_at", core.serialization.date().optional()),
    lastStatusCode: core.serialization.property("last_status_code", core.serialization.number().optional()),
    lastError: core.serialization.property("last_error", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace WebhookDelivery {
    export interface Raw {
        id: string;
        conversation_id: string;
        agent_id: string;
        url: string;
        event: string;
        status: WebhookDeliveryStatus.Raw;
        attempt_count: number;
        last_attempt_at?: string | null;
        last_status_code?: number | null;
        last_error?: string | null;
        created_at: string;
    }
}
