/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";

export const WebhookProbeResult: core.serialization.ObjectSchema<
    serializers.WebhookProbeResult.Raw,
    Speechify.WebhookProbeResult
> = core.serialization.object({
    ok: core.serialization.boolean(),
    statusCode: core.serialization.property("status_code", core.serialization.number().optional()),
    latencyMs: core.serialization.property("latency_ms", core.serialization.number().optional()),
    responseBody: core.serialization.property("response_body", core.serialization.string().optional()),
    signed: core.serialization.boolean(),
    error: core.serialization.string().optional(),
});

export declare namespace WebhookProbeResult {
    export interface Raw {
        ok: boolean;
        status_code?: number | null;
        latency_ms?: number | null;
        response_body?: string | null;
        signed: boolean;
        error?: string | null;
    }
}
