/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Speechify from "../../api/index";
import * as core from "../../core";
import { WidgetConfigStyle } from "./WidgetConfigStyle";
import { WidgetConfigTheme } from "./WidgetConfigTheme";
import { WidgetConfigAvatar } from "./WidgetConfigAvatar";
import { WidgetConfigText } from "./WidgetConfigText";
import { WidgetConfigTerms } from "./WidgetConfigTerms";
import { WidgetConfigTranscript } from "./WidgetConfigTranscript";

export const WidgetConfig: core.serialization.ObjectSchema<serializers.WidgetConfig.Raw, Speechify.WidgetConfig> =
    core.serialization
        .object({
            version: core.serialization.number().optional(),
            style: WidgetConfigStyle.optional(),
            theme: WidgetConfigTheme.optional(),
            avatar: WidgetConfigAvatar.optional(),
            text: WidgetConfigText.optional(),
            terms: WidgetConfigTerms.optional(),
            transcript: WidgetConfigTranscript.optional(),
        })
        .passthrough();

export declare namespace WidgetConfig {
    export interface Raw {
        version?: number | null;
        style?: WidgetConfigStyle.Raw | null;
        theme?: WidgetConfigTheme.Raw | null;
        avatar?: WidgetConfigAvatar.Raw | null;
        text?: WidgetConfigText.Raw | null;
        terms?: WidgetConfigTerms.Raw | null;
        transcript?: WidgetConfigTranscript.Raw | null;
        [key: string]: any;
    }
}
