/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         agentId: "agent_01HS...",
 *         to: "+41791234567",
 *         callerIdNumber: "+12025551234"
 *     }
 *
 * @example
 *     {
 *         agentId: "agent_01HS...",
 *         to: "+41791234567",
 *         dynamicVariables: {
 *             "customer_name": "\"Alice\"",
 *             "order_id": "\"ORD-8821\"",
 *             "outstanding_balance": "142.50"
 *         }
 *     }
 */
export interface CreateOutboundCallRequest {
    /** ID of the agent that handles the answered call. */
    agentId: string;
    /** Destination phone number in E.164 format (e.g. `+12025559876`). */
    to: string;
    /**
     * The number shown to the callee as caller ID, in E.164 format.
     * Defaults to the first outbound-capable number in the workspace.
     * Useful for multi-number campaigns where you want to rotate
     * caller IDs.
     */
    callerIdNumber?: string;
    /**
     * DTMF digits dialed automatically after the call is answered,
     * before the agent begins speaking. Use this for IVR navigation
     * (e.g. `1ww2` presses 1, waits two seconds, presses 2). `w`
     * is a half-second pause; `W` is a one-second pause.
     */
    dtmfPrefix?: string;
    /**
     * Per-call variable overrides merged on top of the agent's stored
     * defaults. Keys must not use the reserved `system__` prefix.
     * Useful for injecting per-call context (customer name, order ID)
     * into the agent prompt.
     */
    dynamicVariables?: Record<string, unknown>;
    /**
     * How long to wait for the callee to answer before abandoning,
     * in milliseconds. Defaults to 30000 (30s). Capped at 80000 (80s).
     */
    ringingTimeoutMs?: number;
    /**
     * Optional per-call override for the AMD routing config. When
     * set, wholesale-replaces the agent's stored AMD shape for
     * this single call (PATCH-replace, not merge). Unlocks the
     * batch-campaign pattern: one agent dialling many recipients
     * with per-row tailored voicemail messages via the existing
     * dynamic_variables substitution. Validation rules match
     * the agent-update boundary.
     */
    amd?: Speechify.AmdConfig;
}
