/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {}
 */
export interface ListConversationsRequest {
    /**
     * Opaque pagination cursor from a previous response.
     */
    cursor?: string;
    /**
     * Max conversations per page (default 50, max 200).
     */
    limit?: number;
    /**
     * Filter to conversations for this agent.
     */
    agentId?: string;
    /**
     * Filter by conversation status.
     */
    status?: Speechify.ConversationStatus;
    /**
     * Filter by transport.
     */
    transport?: Speechify.ConversationTransport;
    /**
     * Filter by caller identity.
     */
    callerIdentity?: string;
    /**
     * Free-text search across conversation content.
     */
    search?: string;
    /**
     * Only conversations started at or after this RFC 3339 timestamp.
     */
    startedAfter?: Date;
    /**
     * Only conversations started at or before this RFC 3339 timestamp.
     */
    startedBefore?: Date;
    /**
     * Minimum conversation duration in milliseconds.
     */
    durationMinMs?: number;
    /**
     * Maximum conversation duration in milliseconds.
     */
    durationMaxMs?: number;
}
