/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListWebhookDeliveriesConversationsRequest {
    /**
     * Opaque pagination cursor from a previous response.
     */
    cursor?: string;
    /**
     * Max deliveries per page (default 50, max 200).
     */
    limit?: number;
}
