/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Speechify from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { SystemToolConfig } from "../../../types/SystemToolConfig";
import { WebhookToolConfig } from "../../../types/WebhookToolConfig";
import { ClientToolConfig } from "../../../types/ClientToolConfig";

export const CreateToolRequestConfig: core.serialization.Schema<
    serializers.tts.CreateToolRequestConfig.Raw,
    Speechify.tts.CreateToolRequestConfig
> = core.serialization.undiscriminatedUnion([SystemToolConfig, WebhookToolConfig, ClientToolConfig]);

export declare namespace CreateToolRequestConfig {
    export type Raw = SystemToolConfig.Raw | WebhookToolConfig.Raw | ClientToolConfig.Raw;
}
