/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         name: "Telnyx BYOC",
 *         kind: "byoc",
 *         direction: "both",
 *         sipAddress: "sip.telnyx.com",
 *         authUsername: "myuser",
 *         authPassword: "mypassword",
 *         transport: "auto",
 *         mediaEncryption: "allow"
 *     }
 */
export interface CreateSipTrunkRequest {
    /** Human-readable name for the trunk. */
    name: string;
    kind: Speechify.SipTrunkKind;
    direction: Speechify.SipTrunkDirection;
    /** SIP endpoint hostname. Required for `kind=byoc`. */
    sipAddress?: string;
    /** SIP digest auth username. */
    authUsername?: string;
    /** SIP digest auth password. Write-only. */
    authPassword?: string;
    /** IP / CIDR allowlist for inbound connections. Empty means any source is accepted. */
    allowedAddresses?: string[];
    /** ISO 3166-1 alpha-2 country for the outbound dial plan. */
    destinationCountry?: string;
    transport?: Speechify.SipTransport;
    mediaEncryption?: Speechify.SipMediaEncryption;
    /** Provider-specific credential blob (for future extensibility). */
    credentials?: Record<string, unknown>;
}
