// This file was auto-generated by Fern from our API Definition.

import type * as Speechify from "../../../../index.js";

/**
 * @example
 *     {
 *         audio_format: "mp3",
 *         input: "Hello! This is the Speechify text-to-speech API.",
 *         model: "simba-english",
 *         voice_id: "george"
 *     }
 */
export interface GetSpeechRequest {
    /** The format for the output audio. Note, that the current default is "wav", but there's no guarantee it will not change in the future. We recommend always passing the specific param you expect. */
    audio_format?: GetSpeechRequest.AudioFormat;
    /**
     * Plain text or SSML to be synthesized to speech.
     * Refer to https://docs.speechify.ai/docs/api-limits for the input size limits.
     * Emotion, Pitch and Speed Rate are configured in the ssml input, please refer to the ssml documentation for more information: https://docs.speechify.ai/docs/ssml#prosody
     */
    input: string;
    /**
     * Language of the input. Follow the format of an ISO 639-1 language code and an ISO 3166-1 region code, separated by a hyphen, e.g. en-US.
     * Please refer to the list of the supported languages and recommendations regarding this parameter: https://docs.speechify.ai/docs/language-support.
     */
    language?: string;
    /** Model used for audio synthesis. `simba-english` is optimized for English, `simba-multilingual` for non-English or mixed input. `simba-3.2` is the streaming-native model with lower TTFB and richer expressivity, and the recommended Simba 3 model. `simba-3.0` is the earlier Simba 3.0 model, still available. `simba-3.0` and `simba-3.2` are currently English only; multilingual coming soon, and non-English voices return 400 until it ships. */
    model?: GetSpeechRequest.Model;
    options?: Speechify.GetSpeechOptionsRequest;
    /** The output audio format as a `codec_sampleRate_bitrate` string. Takes precedence over `audio_format` when set. */
    output_format?: Speechify.AudioOutputFormat;
    /** Id of the voice to be used for synthesizing speech. Refer to /v1/voices endpoint for available voices */
    voice_id: string;
}

export namespace GetSpeechRequest {
    /** The format for the output audio. Note, that the current default is "wav", but there's no guarantee it will not change in the future. We recommend always passing the specific param you expect. */
    export const AudioFormat = {
        Wav: "wav",
        Mp3: "mp3",
        Ogg: "ogg",
        Aac: "aac",
        Pcm: "pcm",
    } as const;
    export type AudioFormat = (typeof AudioFormat)[keyof typeof AudioFormat];
    /** Model used for audio synthesis. `simba-english` is optimized for English, `simba-multilingual` for non-English or mixed input. `simba-3.2` is the streaming-native model with lower TTFB and richer expressivity, and the recommended Simba 3 model. `simba-3.0` is the earlier Simba 3.0 model, still available. `simba-3.0` and `simba-3.2` are currently English only; multilingual coming soon, and non-English voices return 400 until it ships. */
    export const Model = {
        /**
         * simba-english is optimized for English words. */
        SimbaEnglish: "simba-english",
        /**
         * simba-multilingual is optimized for non-English words or mixed languages. */
        SimbaMultilingual: "simba-multilingual",
        /**
         * simba-3.0 is the earlier Simba 3.0 model, still available. Prefer simba-3.2 for the latest quality. Currently English only; non-English voices return 400. */
        Simba30: "simba-3.0",
        /**
         * simba-3.2 is the streaming-native model with lower TTFB and richer expressivity. Currently English only; multilingual coming soon. Non-English voices return 400 until multilingual support ships. */
        Simba32: "simba-3.2",
    } as const;
    export type Model = (typeof Model)[keyof typeof Model];
}
