/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as Speechify from "../../../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../../../serialization/index";
import * as errors from "../../../../../../errors/index";

export declare namespace Callers {
    export interface Options {
        environment?: core.Supplier<environments.SpeechifyEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Callers {
    constructor(protected readonly _options: Callers.Options = {}) {}

    /**
     * List the workspace's callers, ordered by most-recently-seen first.
     * A caller is the per-(tenant, agent, identity) entity that owns
     * long-term memories and conversation history.
     *
     * @param {Speechify.agent.ListCallersRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     *
     * @example
     *     await client.agent.callers.list()
     */
    public async list(
        request: Speechify.agent.ListCallersRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<core.Page<Speechify.Caller>> {
        const list = async (request: Speechify.agent.ListCallersRequest): Promise<Speechify.ListCallersResponse> => {
            const { agentId, q, lastSeenAfter, cursor, limit } = request;
            const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
            if (agentId != null) {
                _queryParams["agent_id"] = agentId;
            }
            if (q != null) {
                _queryParams["q"] = q;
            }
            if (lastSeenAfter != null) {
                _queryParams["last_seen_after"] = lastSeenAfter.toISOString();
            }
            if (cursor != null) {
                _queryParams["cursor"] = cursor;
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            const _response = await core.fetcher({
                url: urlJoin(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SpeechifyEnvironment.Default,
                    "v1/agents/callers",
                ),
                method: "GET",
                headers: {
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@speechify/api",
                    "X-Fern-SDK-Version": "1.0.2",
                    "User-Agent": "@speechify/api/1.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                    ...requestOptions?.headers,
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
            });
            if (_response.ok) {
                return serializers.ListCallersResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Speechify.BadRequestError(_response.error.body);
                    default:
                        throw new errors.SpeechifyError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/callers.");
                case "unknown":
                    throw new errors.SpeechifyError({
                        message: _response.error.errorMessage,
                    });
            }
        };
        return new core.Pageable<Speechify.ListCallersResponse, Speechify.Caller>({
            response: await list(request),
            hasNextPage: (response) => response?.nextCursor != null,
            getItems: (response) => response?.callers ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * Fetch a single caller by id. Returns 404 for soft-deleted or
     * foreign-tenant rows — GDPR-purged callers appear as "not found"
     * to the API.
     *
     * @param {string} id - Caller ID.
     * @param {Speechify.agent.GetCallersRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.callers.get("id")
     */
    public async get(
        id: string,
        request: Speechify.agent.GetCallersRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<Speechify.GetCallerResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/callers/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.GetCallerResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling GET /v1/agents/callers/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Soft-delete the caller AND cascade soft-delete every memory row
     * pointing at it. Conversations survive (forensic / billing records)
     * but their caller pointer surfaces as "deleted" through the API.
     *
     * Idempotent — re-deleting an already-purged caller returns
     * `{caller_purged: 0, memories_purged: 0}`. Audit row counts
     * accompany every response so a privacy operator has direct
     * evidence of the purge without re-querying.
     *
     * @param {string} id - Caller ID.
     * @param {Speechify.agent.DeleteCallersRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agent.callers.delete("id")
     */
    public async delete(
        id: string,
        request: Speechify.agent.DeleteCallersRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<Speechify.DeleteCallerResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/callers/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.DeleteCallerResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SpeechifyError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling DELETE /v1/agents/callers/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Update the customer-editable fields on a caller. PATCH semantics:
     * omitted fields are unchanged, present fields overwrite. To clear
     * a nullable field (`display_name`, `external_ref`) pass an empty
     * string. `metadata` REPLACES the existing JSONB blob when supplied.
     *
     * @param {string} id - Caller ID.
     * @param {Speechify.agent.UpdateCallerRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     * @throws {@link Speechify.NotFoundError}
     *
     * @example
     *     await client.agent.callers.update("id")
     */
    public async update(
        id: string,
        request: Speechify.agent.UpdateCallerRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<Speechify.GetCallerResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpeechifyEnvironment.Default,
                `v1/agents/callers/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@speechify/api",
                "X-Fern-SDK-Version": "1.0.2",
                "User-Agent": "@speechify/api/1.0.2",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.agent.UpdateCallerRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.GetCallerResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                skipValidation: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Speechify.BadRequestError(_response.error.body);
                case 404:
                    throw new Speechify.NotFoundError(_response.error.body);
                default:
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpeechifyError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.SpeechifyTimeoutError("Timeout exceeded when calling PATCH /v1/agents/callers/{id}.");
            case "unknown":
                throw new errors.SpeechifyError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * List one page of memories belonging to the caller, newest first.
     * Soft-deleted memories AND memories whose parent caller is
     * soft-deleted are hidden — the GDPR purge semantics require the
     * API to behave as if those rows do not exist.
     *
     * @param {string} id - Caller ID.
     * @param {Speechify.agent.ListMemoriesCallersRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     *
     * @example
     *     await client.agent.callers.listMemories("id")
     */
    public async listMemories(
        id: string,
        request: Speechify.agent.ListMemoriesCallersRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<core.Page<Speechify.CallerMemoryItem>> {
        const list = async (
            request: Speechify.agent.ListMemoriesCallersRequest,
        ): Promise<Speechify.ListCallerMemoriesResponse> => {
            const { cursor, limit } = request;
            const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
            if (cursor != null) {
                _queryParams["cursor"] = cursor;
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            const _response = await core.fetcher({
                url: urlJoin(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SpeechifyEnvironment.Default,
                    `v1/agents/callers/${encodeURIComponent(id)}/memories`,
                ),
                method: "GET",
                headers: {
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@speechify/api",
                    "X-Fern-SDK-Version": "1.0.2",
                    "User-Agent": "@speechify/api/1.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                    ...requestOptions?.headers,
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
            });
            if (_response.ok) {
                return serializers.ListCallerMemoriesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Speechify.BadRequestError(_response.error.body);
                    default:
                        throw new errors.SpeechifyError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.SpeechifyTimeoutError(
                        "Timeout exceeded when calling GET /v1/agents/callers/{id}/memories.",
                    );
                case "unknown":
                    throw new errors.SpeechifyError({
                        message: _response.error.errorMessage,
                    });
            }
        };
        return new core.Pageable<Speechify.ListCallerMemoriesResponse, Speechify.CallerMemoryItem>({
            response: await list(request),
            hasNextPage: (response) => response?.nextCursor != null,
            getItems: (response) => response?.memories ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * List one page of conversations belonging to the caller, newest
     * started first. Same wire envelope as the workspace-wide
     * `GET /v1/agents/conversations`, narrowed to one caller.
     *
     * @param {string} id - Caller ID.
     * @param {Speechify.agent.ListConversationsCallersRequest} request
     * @param {Callers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Speechify.BadRequestError}
     *
     * @example
     *     await client.agent.callers.listConversations("id")
     */
    public async listConversations(
        id: string,
        request: Speechify.agent.ListConversationsCallersRequest = {},
        requestOptions?: Callers.RequestOptions,
    ): Promise<core.Page<Speechify.Conversation>> {
        const list = async (
            request: Speechify.agent.ListConversationsCallersRequest,
        ): Promise<Speechify.ListCallerConversationsResponse> => {
            const { cursor, limit } = request;
            const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
            if (cursor != null) {
                _queryParams["cursor"] = cursor;
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            const _response = await core.fetcher({
                url: urlJoin(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SpeechifyEnvironment.Default,
                    `v1/agents/callers/${encodeURIComponent(id)}/conversations`,
                ),
                method: "GET",
                headers: {
                    Authorization: await this._getAuthorizationHeader(),
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@speechify/api",
                    "X-Fern-SDK-Version": "1.0.2",
                    "User-Agent": "@speechify/api/1.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                    ...requestOptions?.headers,
                },
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
            });
            if (_response.ok) {
                return serializers.ListCallerConversationsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                });
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Speechify.BadRequestError(_response.error.body);
                    default:
                        throw new errors.SpeechifyError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.SpeechifyError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                    });
                case "timeout":
                    throw new errors.SpeechifyTimeoutError(
                        "Timeout exceeded when calling GET /v1/agents/callers/{id}/conversations.",
                    );
                case "unknown":
                    throw new errors.SpeechifyError({
                        message: _response.error.errorMessage,
                    });
            }
        };
        return new core.Pageable<Speechify.ListCallerConversationsResponse, Speechify.Conversation>({
            response: await list(request),
            hasNextPage: (response) => response?.nextCursor != null,
            getItems: (response) => response?.conversations ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = (await core.Supplier.get(this._options.token)) ?? process?.env["SPEECHIFY_API_KEY"];
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
