/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Speechify from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { BatchRecipientRequest } from "../../../../../../types/BatchRecipientRequest";

export const CreateBatchCallRequest: core.serialization.Schema<
    serializers.agent.CreateBatchCallRequest.Raw,
    Speechify.agent.CreateBatchCallRequest
> = core.serialization.object({
    name: core.serialization.string(),
    agentId: core.serialization.property("agent_id", core.serialization.string()),
    phoneNumberId: core.serialization.property("phone_number_id", core.serialization.string().optional()),
    scheduledAt: core.serialization.property("scheduled_at", core.serialization.date().optional()),
    ringingTimeoutMs: core.serialization.property("ringing_timeout_ms", core.serialization.number().optional()),
    recipients: core.serialization.list(BatchRecipientRequest),
});

export declare namespace CreateBatchCallRequest {
    export interface Raw {
        name: string;
        agent_id: string;
        phone_number_id?: string | null;
        scheduled_at?: string | null;
        ringing_timeout_ms?: number | null;
        recipients: BatchRecipientRequest.Raw[];
    }
}
