/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../../../index";

/**
 * @example
 *     {
 *         name: "Appointment reminders",
 *         agentId: "agent_01HS...",
 *         recipients: [{
 *                 phone: "+14155551234",
 *                 dynamicVars: {
 *                     "first_name": "Alice",
 *                     "appointment_date": "May 5th at 2pm"
 *                 }
 *             }, {
 *                 phone: "+14155555678",
 *                 dynamicVars: {
 *                     "first_name": "Bob",
 *                     "appointment_date": "May 6th at 10am"
 *                 }
 *             }]
 *     }
 *
 * @example
 *     {
 *         name: "Monday morning follow-ups",
 *         agentId: "agent_01HS...",
 *         scheduledAt: "2025-05-05T09:00:00Z",
 *         recipients: [{
 *                 phone: "+14155551234",
 *                 dynamicVars: {
 *                     "first_name": "Alice"
 *                 }
 *             }]
 *     }
 */
export interface CreateBatchCallRequest {
    /** Human-readable batch name. */
    name: string;
    /** Agent that handles each call. */
    agentId: string;
    /** Caller-ID override. Falls back to the agent's bound number. */
    phoneNumberId?: string;
    /** Schedule the batch for a future time (RFC 3339). Omit to start immediately. */
    scheduledAt?: Date;
    /**
     * Ringing timeout in milliseconds applied to every call in the
     * batch (how long each recipient rings before the dial gives
     * up). Range 1000-80000 (1-80s). Omit to use the 30s default.
     * The console collects this in seconds and converts to
     * milliseconds.
     */
    ringingTimeoutMs?: number;
    recipients: Speechify.BatchRecipientRequest[];
}
