/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListMemoriesAgentRequest {
    /**
     * Maximum rows to return. Defaults to 100, capped at 200.
     */
    limit?: number;
    /**
     * Number of rows to skip. Combine with `limit` to page through older memories.
     */
    offset?: number;
}
