/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../index";

/**
 * @example
 *     {}
 */
export interface RunAllTestsRequest {
    configOverride?: Speechify.TestRunConfigOverride;
    /**
     * Targets a specific flow version (an `agent_versions` row)
     * instead of the agent's active flow — version-targeted
     * regression. Must be a flow version of the agent under test.
     * Raw UUID; flow versions carry no prefixed wire id.
     */
    flowVersionId?: string;
}
