/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../index";

/**
 * @example
 *     {
 *         variables: [{
 *                 key: "product_name",
 *                 type: "string",
 *                 default: "Speechify",
 *                 description: "Product the agent is supporting."
 *             }, {
 *                 key: "support_tier",
 *                 type: "number",
 *                 default: 1
 *             }, {
 *                 key: "account_metadata",
 *                 type: "json",
 *                 description: "Arbitrary account context injected into tool bodies."
 *             }]
 *     }
 */
export interface UpdateDynamicVariablesRequest {
    /** The new variable list. Replaces the existing list entirely. */
    variables: Speechify.DynamicVariable[];
}
