/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../index";

/**
 * @example
 *     {
 *         criteria: [{
 *                 id: "id",
 *                 name: "name",
 *                 description: "description"
 *             }],
 *         dataCollection: [{
 *                 key: "key",
 *                 description: "description",
 *                 type: "string"
 *             }]
 *     }
 */
export interface UpdateEvaluationConfigRequest {
    criteria: Speechify.EvaluationCriterion[];
    dataCollection: Speechify.DataCollectionField[];
}
