/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Speechify from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateAgentRequest {
    name?: string;
    prompt?: string;
    firstMessage?: string;
    language?: string;
    /**
     * LLM backend. Send an empty string together with
     * `llm_model: ""` to clear the pair to the platform default
     * (today: Speechify Kimi K2.6). Sending one populated and
     * one empty is rejected as a 400. Omit both to leave the
     * stored pair unchanged. Switching to a non-`custom` provider
     * clears any stored `llm_base_url` / `llm_api_key` /
     * `llm_extra_body`.
     */
    llmProvider?: Speechify.UpdateAgentRequestLlmProvider;
    /**
     * Chat model slug. Empty string + empty `llm_provider`
     * clears the pair to the platform default. For `openai` /
     * `speechify` the (provider, model) pair must be in the
     * allowed table; for `custom` it is free-form.
     */
    llmModel?: string;
    /**
     * Custom-endpoint base URL. Required when the resulting
     * provider is `custom`, rejected otherwise.
     */
    llmBaseUrl?: string;
    /**
     * Bearer key for the custom endpoint. Write-only. Omit to
     * keep the stored key, send "" to clear it, send a value to
     * replace it. Rejected for non-`custom` providers.
     */
    llmApiKey?: string;
    /**
     * JSON object forwarded to the custom endpoint as
     * chat.completions `extra_body`. Omit to leave unchanged;
     * a JSON object (including `{}`) replaces it. Valid only
     * when the resulting provider is `custom`.
     */
    llmExtraBody?: Record<string, unknown>;
    voiceId?: string;
    /** Sampling temperature in the range 0.0–1.0. Omit to leave unchanged. */
    temperature?: number;
    widgetConfig?: Speechify.WidgetConfig;
    isPublic?: boolean;
    allowedOrigins?: string[];
    /**
     * When supplied, replaces the stored list. Pass an empty
     * array to clear enforcement (public agent is open again).
     * Omit the field to leave the existing value unchanged.
     */
    hostnameAllowlist?: string[];
    memoryEnabled?: boolean;
    memoryRetentionDays?: number;
    webhookUrl?: string;
    /** Rotate the HMAC secret. Write-only. */
    webhookSecret?: string;
    /** AMD routing config (PATCH-replace, wholesale). Omit to leave the stored config unchanged. */
    amd?: Speechify.AmdConfig;
    saveAudioRecording?: boolean;
    navigatorMode?: boolean;
    /** Per-agent kill switch for the IVR-memory cache lookup. nil/omit = unchanged. */
    ivrMemoryEnabled?: boolean;
    ttsSpeakingRate?: number | null;
    /**
     * Two-headed clear: PATCH cannot distinguish "absent" from
     * "explicit null" reliably across stacks. Setting this to
     * `true` resets `tts_speaking_rate` to the voice default.
     * If both are sent, `clear_tts_speaking_rate` wins.
     */
    clearTtsSpeakingRate?: boolean;
    ttsPlaybackRate?: number | null;
    /**
     * Two-headed clear, mirroring `clear_tts_speaking_rate`.
     * Setting this to `true` resets `tts_playback_rate` to null
     * (no post-process). If both fields are sent,
     * `clear_tts_playback_rate` wins.
     */
    clearTtsPlaybackRate?: boolean;
    /**
     * Per-agent silence-wait override (seconds). See the field
     * on Agent for semantics. Range 0.0..5.0; null is allowed
     * but `clear_response_delay_seconds=true` is the canonical
     * way to revert to the stack default.
     */
    responseDelaySeconds?: number | null;
    /**
     * Two-headed clear, mirroring `clear_tts_playback_rate`.
     * Setting this to `true` resets `response_delay_seconds` to
     * null (revert to the stack default). If both are sent,
     * `clear_response_delay_seconds` wins.
     */
    clearResponseDelaySeconds?: boolean;
    /**
     * Per-agent silence-tolerance override. Send `0` to clear
     * the override and fall back to the platform default.
     * Negative values are rejected.
     */
    inactivityTimeoutSeconds?: number;
    /**
     * Pre-mixed ambient bed slug. Send empty string ("") to
     * disable the bed, which also clears `background_noise_volume`.
     */
    backgroundNoisePreset?: Speechify.UpdateAgentRequestBackgroundNoisePreset;
    /**
     * Volume of the background-noise bed (0..1). Ignored when
     * the preset is empty; clearing the preset also clears
     * this field server-side.
     */
    backgroundNoiseVolume?: number;
    /**
     * Streaming-STT stack override. Send an empty string ("") to
     * clear the override and fall back to the worker default
     * (today: whisper-v3). Any non-empty value must be a known
     * stack name.
     */
    sttOverride?: Speechify.UpdateAgentRequestSttOverride;
}
